#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
from pathlib import Path

sc = json.loads(Path(r"D:\Gimbal\Gimbal\gimbal-tmp\Scenario_Test_15.json").read_text(encoding="utf-8"))
b5 = sc["steps"][4]["request"]["body"]

user_data = {
    "client_expand_name": "孙硕", "client_expand_id": "250", "m_delivery_type": "",
    "customer_id": "16", "customer_name": "兰森玻璃（青岛）有限公司",
    "receive_time_limit": "7", "deposit_refund_day": "15", "deposit_settlement_date": "30",
    "service_id": "55", "service_name": "曲静霞", "operator_id": "67", "operator_name": "律欣怡",
    "customer_contact_id": "", "customer_contact_name": "",
    "main_sort": "易汇智,易航道", "policy_id": "112", "policy_name": "【SPV对客】易汇智",
    "policy_type": "JSZX",
    "settle_type": "2", "settle_type_name": "票结", "product_id": "3", "product_name": "票结-不延长-保证金",
    "deposit_type": "1", "deposit_type_name": "有", "period_delay_type": "2", "period_delay_type_name": "不延长",
    "service_items": ["booking_space", "insurance"],
    "business_type": "1", "trade_term": "CIF", "carrier": "ACL", "carrier_id": "1",
    "bl_no": "GET_TEST_29", "track_bl_no": "GET_TEST_29",
    "etd": 1781712000, "atd": 1781712000, "ship_name": "1", "voy": "1",
    "pol": "QINGDAO,CHINA", "pot": "", "pod": "LONG BEACH,CA,UNITED STATES",
    "del": "LONG BEACH,CA,UNITED STATES", "country_name": "UNITED STATES",
    "airline_type": "美西", "ocean_type": "远洋",
    "terms_payment": "T/T", "terms_transport": "CY/CY", "pay_type": "FREIGHT PREPAID",
    "customer_order_sn": "", "terms_shipment": "", "shipper": "1", "consignee": "1",
    "notifier": "1", "ship_mark": "", "commodity": "", "notes": "", "cargo_type": "", "packer": "",
    "num": "1", "gross_weight": "1.000", "bulk": None,
    "sea_trans_cost": "2500.00", "teu": "5", "volume": "2*40HQ+1*20GP", "volume_desc": "普柜",
    "order_sn": "", "status": "1", "sea_trans_currency": "USD",
    "container": [{"order_container_id": "335009642855792640", "box_type": "40HQ", "box_num": "2",
                   "box_no": ["", ""], "seal_number": ["", ""], "sea_trans_unit_price": 1000},
                  {"order_container_id": "335009642855793664", "box_type": "20GP", "box_num": "1",
                   "box_no": [""], "seal_number": [""], "sea_trans_unit_price": 500}],
    "message_board": [], "customer_file_list": [],
    "supplier": [
        {"order_supplier_id": "335009604670849024", "order_id": "335009603169288192",
         "isset_supplier": "1", "is_primary": "1", "supplier_id": "12",
         "supplier_name": "青岛泰瑞达国际货运代理有限公司", "settle_object_id": "43",
         "user_id": "335", "user_name": "王滨恺", "service_item": "booking_space",
         "supplier_period": "30", "settlement_date": "20", "supplier_pay_date": "0",
         "is_manual": "0", "sys_upttime": "2026-07-13 18:48:33", "pay_time_limit": "5",
         "supplier_pay_date_desc": "", "supplier_label": "青岛泰瑞达国际货运代理有限公司-订舱",
         "service_item_name": "订舱", "isset_fee": False},
        {"order_supplier_id": "335009604670850048", "order_id": "335009603169288192",
         "isset_supplier": "1", "is_primary": "1", "supplier_id": "", "supplier_name": "",
         "settle_object_id": "0", "user_id": "335", "user_name": "王滨恺",
         "service_item": "insurance", "supplier_period": "0", "settlement_date": "0",
         "supplier_pay_date": "0", "is_manual": "0", "sys_upttime": "2026-07-13 18:48:33",
         "pay_time_limit": "", "supplier_pay_date_desc": "", "supplier_label": "-保险",
         "service_item_name": "保险", "isset_fee": False}],
    "remark": "AAA",
    "order_id": "335009603169288192", "order_no": "YWDD20260713108437",
    "customer_category": ",2,", "customer_tax_number": "91370283591262431N",
    "customer_address_cn": "山东省青岛市平度市南村镇东王府庄村",
    "customer_contact_phone": "", "customer_main_id": "31",
    "customer_main_name": "青岛易汇智供应链管理有限公司", "business_main_id": "1",
    "business_main_name": "青岛易航道物流科技有限公司",
    "fund_code": "", "fund_name": None,
    "track_atd": "0", "track_eta": "0", "track_ata": "0", "track_stcs": "0",
    "track_ship_name": None, "track_voy": None,
    "finance_date": "1781712000",
    "pol_cn": "青岛港", "pol_country_id": "1", "pol_country": "CHINA", "pol_country_cn": "中国",
    "pod_cn": "长滩", "pot_cn": "", "del_cn": "长滩",
    "country_id": "893", "country_name_cn": "美国",
    "customer_period": "60", "customer_settlement_date": "10",
    "period_rule": "1", "term_rule_name": None,
    "customer_due_date": "0", "customer_put_date": "0",
    "customer_payment_collection_date": None, "customer_put_date_manual": "0",
    "customer_put_writeoff_date": "", "supplier_due_date": "0",
    "discount_start": "0", "discount_rule": "", "discount_end": "0", "discount_ratio": "",
    "discount_status": "2", "discount_currency": "",
    "book_upload_date": "0", "trans_cost_put_preserve_date": "0", "bl_no_upload_date": "0",
    "supplier_invoice_date": "0", "supplier_invoice_taketime": "", "real_cost_date": "0",
    "customer_invoice_request_date": "0", "first_financing_doc_ok_date": "0",
    "second_financing_doc_ok_date": "0", "insurance_doc_ok_date": "0", "customer_confirm_date": "0",
    "is_delayed_recovery": "否", "delayed_recovery_usd": "", "delayed_recovery_cny": "",
    "delayed_time": "", "expect_fee_status": "0", "real_fee_status": "0",
    "fee_lock_status": "0", "pay_account_status": "0", "account_status": "0",
    "real_pay_usd": "0.00", "real_pay_cny": "0.00", "real_put_usd": "0.00", "real_put_cny": "0.00",
    "real_put_discount_rate": "0.00", "exchange_rate": "7.0000",
    "folde_pay_usd": "0.00", "folde_put_usd": "0.00", "folde_pay_total": "0.00", "folde_put_total": "0.00",
    "gross_margin": "0.00", "gross_margin_rate": "0.00",
    "is_special_pay": "0", "is_loan_before_invoice": "0", "is_fee_miss": "0", "fee_miss_name": "",
    "cancel_remark": "", "cancel_time": "0", "effective_id": "0", "effective_by": "",
    "effective_time": "0", "create_id": "828", "create_by": "GIMBAL",
    "create_time": "1783939713", "update_id": "828", "update_by": "GIMBAL",
    "update_time": "1783939723", "delete_time": "0", "business_time": "0",
    "main_ids": ",31,1,",
    "reverse_status": "0", "proprietary_business_status": "0",
    "loan_status": None, "first_status": None, "second_status": None,
    "loan_pay_status": "", "change_type": "0", "copy_order_id": "0",
    "real_fee_locked": False, "is_usd_project": "2", "pay_status": "1", "is_sync_es": "0",
    "expect_discount_status": "0", "real_discount_status": "0",
    "entrust_status": 2,
    "audit_type": "", "is_system_generate": "0", "is_financing": "0",
    "confirm_status": "0", "is_traverse": "0",
    "financing_apply_amount": "0.00", "financing_apply_amount_cny": "0.00",
    "financing_apply_amount_usd": "0.00",
    "sys_upttime": "2026-07-13 18:48:43",
    "customer_put_date_desc": "", "deposit_refund_month": "0",
    "payment_type": "1",
    "reverse_status_name": "否", "is_delayed_recovery_name": "否",
    "order_finance_arr": [], "order_main_bank_arr": [], "order_sub": [], "order_sub_no": "",
    "service_project": {"booking_space": False, "customs_clearance": False, "manifest": False,
                       "insurance": False, "trucking": False},
    "service_project_amount": {"booking_space": False, "customs_clearance": False, "manifest": False,
                              "insurance": False, "trucking": False},
    "finance_status": True, "main_ids_name": "易汇智,易航道",
    "policy_main_arr": [{"fee_main_id": "31", "main_name": "青岛易汇智供应链管理有限公司"},
                       {"fee_main_id": "1", "main_name": "青岛易航道物流科技有限公司"}],
    "policy_type_name": "结算业务", "business_type_name": "海运整箱",
    "cargo_type_name": "", "period_rule_name": "25日后订单截转下月计算账期（CIF特殊规则1、FOB结算规则1）",
    "trade_term_name": "CIF", "carrier_name": "大西洋航运",
    "terms_transport_name": "CY/CY", "terms_payment_name": "T/T",
    "pay_type_name": "FREIGHT PREPAID", "m_delivery_type_name": "",
    "payment_type_name": "确定性付款",
    "audit": [], "enable": "1", "policy_match": "semi", "policy_match_name": "手动选择",
    "real_discount_status_name": "—", "expect_discount_status_name": "—",
    "expect_policy_status_name": "", "policy_status_name": "",
    "subsidy_category_name": "—", "expect_subsidy_category_name": "—",
    "real_subsidy_category_name": "—",
    "action": "submit", "order_file": []
}

# 关键差异字段
print(f"Step 5 body keys count: {len(b5)}, User data keys count: {len(user_data)}")
print()
print("=== 关键差异字段 ===")
CRITICAL = [
    ("entrust_status", "用户=2 (订单已提交)"),
    ("remark", "用户='AAA'"),
    ("action", "用户='submit'"),
    ("pay_time_limit", "用户在 supplier[0]='5', supplier[1]=''"),
    ("period_rule", "用户='1', Step5='0'"),
    ("deposit_refund_month", "用户='0', Step5=None"),
    ("status", "用户='1', Step5=1"),
    ("customer_tax_number", "用户有值"),
    ("customer_address_cn", "用户有值"),
    ("finance_status", "用户=True"),
    ("is_usd_project", "用户='2'"),
    ("pay_status", "用户='1'"),
    ("is_financing", "用户='0'"),
    ("confirm_status", "用户='0'"),
    ("main_ids", "用户=',31,1,'"),
    ("main_ids_name", "用户='易汇智,易航道'"),
    ("policy_main_arr", "用户有2项"),
    ("policy_type_name", "用户='结算业务'"),
    ("period_rule_name", "用户='25日后订单截转下月计算账期...'"),
    ("service_project", "用户有 dict"),
    ("carrier_name", "用户='大西洋航运'"),
    ("trade_term_name", "用户='CIF'"),
    ("finance_date", "用户='1781712000'"),
    ("fund_code", "用户=''"),
    ("payment_type", "用户='1'"),
    ("payment_type_name", "用户='确定性付款'"),
    ("sys_upttime", "用户='2026-07-13 18:48:43'"),
]
for k, hint in CRITICAL:
    s5v = b5.get(k, "<MISSING>")
    uv = user_data.get(k, "<MISSING>")
    same = "OK" if s5v == uv else "DIFF"
    if k == "remark":
        print(f"  [{same}] {k:30s} Step5={s5v!r:40s} User={uv!r:30s}  {hint}")
    elif k == "pay_time_limit":
        s5_sup0 = b5.get("supplier", [{}])[0].get("pay_time_limit", "<MISSING>")
        print(f"  [{same}] {k:30s} Step5.sup[0]={s5_sup0!r:10s} User.sup[0]={user_data['supplier'][0].get(k, '?')!r:10s}  {hint}")
    else:
        s5s = repr(s5v) if not isinstance(s5v, (list, dict)) else f"[{type(s5v).__name__}]"
        uvs = repr(uv) if not isinstance(uv, (list, dict)) else f"[{type(uv).__name__}]"
        print(f"  [{same}] {k:30s} Step5={s5s:35s} User={uvs:25s}  {hint}")