"""fin.order.order_add —— 委托订舱下单接口契约。在 scen_test_14 中出现2次。"""

from typing import Final

from gimbal_plate.systems.fin.system_info import (
    FIN_DEFAULT_AUTHOR,
    FIN_DEFAULT_MODULE,
    FIN_DEFAULT_OWNER,
    FIN_DEFAULT_PRIORITY,
    FIN_DEFAULT_TAGS,
    FIN_DEFAULT_VERSION,
    FIN_SYSTEM,
)
from gimbal_plate.schema.endpoint import (
    ApiSpec,
    EndpointSpec,
    DeclarationEntry,
    RequestSpec,
    ResponseSpec,
    EndpointMetadata,
)


ORDER_ORDER_ADD: Final[EndpointSpec] = EndpointSpec(
    id="fin.order.order_add",
    system=FIN_SYSTEM,
    service="fin-service",
    name="委托订舱下单",
    description="由 Scenario_Test_14 提取: 委托订舱下单",
    api=ApiSpec(service="fin-service", method="POST", path="/api/order/order/orderAdd", auth="bearer", timeout_seconds=30.0),
    request=RequestSpec(
        body_type="json",
        declarations=[
        DeclarationEntry(name='client_expand_name', path='$.client_expand_name', type='string', example='唐欣雨', ui_kind='text'),
        DeclarationEntry(name='m_delivery_type', path='$.m_delivery_type', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='customer_id', path='$.customer_id', type='string', example='320', ui_kind='text'),
        DeclarationEntry(name='customer_name', path='$.customer_name', type='string', example='山东悦慕食品有限公司', ui_kind='text'),
        DeclarationEntry(name='receive_time_limit', path='$.receive_time_limit', type='string', example='20', ui_kind='text'),
        DeclarationEntry(name='deposit_refund_day', path='$.deposit_refund_day', type='string', example='180', ui_kind='text'),
        DeclarationEntry(name='deposit_settlement_date', path='$.deposit_settlement_date', type='string', example='30', ui_kind='text'),
        DeclarationEntry(name='service_id', path='$.service_id', type='string', example='55', ui_kind='text'),
        DeclarationEntry(name='service_name', path='$.service_name', type='string', example='曲静霞', ui_kind='text'),
        DeclarationEntry(name='operator_id', path='$.operator_id', type='string', example='336', ui_kind='text'),
        DeclarationEntry(name='operator_name', path='$.operator_name', type='string', example='闫航', ui_kind='text'),
        DeclarationEntry(name='customer_contact_id', path='$.customer_contact_id', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='customer_contact_name', path='$.customer_contact_name', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='main_sort', path='$.main_sort', type='string', example='易汇瀚,易海,易航道', ui_kind='text'),
        DeclarationEntry(name='policy_id', path='$.policy_id', type='string', example='134', ui_kind='text'),
        DeclarationEntry(name='policy_name', path='$.policy_name', type='string', example='【SPV对客】易汇瀚（仅人民币）', ui_kind='text'),
        DeclarationEntry(name='policy_type', path='$.policy_type', type='string', example='JSZX', ui_kind='text'),
        DeclarationEntry(name='settle_type', path='$.settle_type', type='string', example='1', ui_kind='text'),
        DeclarationEntry(name='settle_type_name', path='$.settle_type_name', type='string', example='月结', ui_kind='text'),
        DeclarationEntry(name='product_id', path='$.product_id', type='string', example='4', ui_kind='text'),
        DeclarationEntry(name='product_name', path='$.product_name', type='string', example='月结-延长-保证金', ui_kind='text'),
        DeclarationEntry(name='deposit_type', path='$.deposit_type', type='string', example='1', ui_kind='text'),
        DeclarationEntry(name='deposit_type_name', path='$.deposit_type_name', type='string', example='有', ui_kind='text'),
        DeclarationEntry(name='period_delay_type', path='$.period_delay_type', type='string', example='1', ui_kind='text'),
        DeclarationEntry(name='period_delay_type_name', path='$.period_delay_type_name', type='string', example='延长', ui_kind='text'),
        DeclarationEntry(name='service_items', path='$.service_items', type='array', example=['booking_space'], ui_kind='json'),
        DeclarationEntry(name='business_type', path='$.business_type', type='string', example='1', ui_kind='text'),
        DeclarationEntry(name='trade_term', path='$.trade_term', type='string', example='CIF', ui_kind='text'),
        DeclarationEntry(name='carrier', path='$.carrier', type='string', example='COSCO', ui_kind='text'),
        DeclarationEntry(name='carrier_id', path='$.carrier_id', type='string', example='16', ui_kind='text'),
        DeclarationEntry(name='bl_no', path='$.bl_no', type='string', example='${var.bl_no}', ui_kind='text'),
        DeclarationEntry(name='track_bl_no', path='$.track_bl_no', type='string', example='${var.bl_no}', ui_kind='text'),
        DeclarationEntry(name='etd', path='$.etd', type='integer', example=1782316800, ui_kind='number'),
        DeclarationEntry(name='atd', path='$.atd', type='integer', example=1782835200, ui_kind='number'),
        DeclarationEntry(name='ship_name', path='$.ship_name', type='string', example='OOCL FRANCE', ui_kind='text'),
        DeclarationEntry(name='voy', path='$.voy', type='string', example='068E', ui_kind='text'),
        DeclarationEntry(name='pol', path='$.pol', type='string', example='QINGDAO,CHINA', ui_kind='text'),
        DeclarationEntry(name='pot', path='$.pot', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='pod', path='$.pod', type='string', example='ANTING,CHINA', ui_kind='text'),
        DeclarationEntry(name='del', path='$.del', type='string', example='ANTING,CHINA', ui_kind='text'),
        DeclarationEntry(name='country_name', path='$.country_name', type='string', example='CHINA', ui_kind='text'),
        DeclarationEntry(name='airline_type', path='$.airline_type', type='string', example='中国', ui_kind='text'),
        DeclarationEntry(name='ocean_type', path='$.ocean_type', type='string', example='近洋', ui_kind='text'),
        DeclarationEntry(name='terms_payment', path='$.terms_payment', type='string', example='T/T', ui_kind='text'),
        DeclarationEntry(name='terms_transport', path='$.terms_transport', type='string', example='CY/CY', ui_kind='text'),
        DeclarationEntry(name='pay_type', path='$.pay_type', type='string', example='FREIGHT PREPAID', ui_kind='text'),
        DeclarationEntry(name='customer_order_sn', path='$.customer_order_sn', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='terms_shipment', path='$.terms_shipment', type='string', example='Codfish', ui_kind='text'),
        DeclarationEntry(name='shipper', path='$.shipper', type='string', example='Codfish', ui_kind='text'),
        DeclarationEntry(name='consignee', path='$.consignee', type='string', example='Codfish', ui_kind='text'),
        DeclarationEntry(name='notifier', path='$.notifier', type='string', example='Codfish', ui_kind='text'),
        DeclarationEntry(name='ship_mark', path='$.ship_mark', type='string', example='Codfish', ui_kind='text'),
        DeclarationEntry(name='commodity', path='$.commodity', type='string', example='Codfish', ui_kind='text'),
        DeclarationEntry(name='cargo_type', path='$.cargo_type', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='packer', path='$.packer', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='num', path='$.num', type='string', example='1872', ui_kind='text'),
        DeclarationEntry(name='gross_weight', path='$.gross_weight', type='string', example='26800.000', ui_kind='text'),
        DeclarationEntry(name='bulk', path='$.bulk', type='string', example='60.000', ui_kind='text'),
        DeclarationEntry(name='sea_trans_cost', path='$.sea_trans_cost', type='string', example='1.00', ui_kind='text'),
        DeclarationEntry(name='teu', path='$.teu', type='string', example='2', ui_kind='text'),
        DeclarationEntry(name='volume', path='$.volume', type='string', example='1*40HQ', ui_kind='text'),
        DeclarationEntry(name='volume_desc', path='$.volume_desc', type='string', example='普柜', ui_kind='text'),
        DeclarationEntry(name='order_sn', path='$.order_sn', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='status', path='$.status', type='integer', example=2, ui_kind='number'),
        DeclarationEntry(name='sea_trans_currency', path='$.sea_trans_currency', type='string', example='USD', ui_kind='text'),
        # 2026-09-05 补全:行形状按本条 example 三方印证(order_customer_container
        # curl / Scenario_Test_14 转储同款)声明 children,行内业务键回到树行组
        # 渲染;不带 default/example → platform 导出 D7 深层无值不落 None 骨架
        # 同日 P2:box_no/seal_number 噪声子数组盖 collapse(区块级折叠,
        # 前端默认收起,点击展开);container 本体保持 form(最常编辑)
        DeclarationEntry(name='container', path='$.container', type='array', example=[{'order_container_id': '', 'box_type': '40HQ', 'box_num': '1', 'box_no': [''], 'seal_number': [''], 'sea_trans_unit_price': 1}], ui_kind='json',
            children=[
                DeclarationEntry(name='order_container_id', path='$.container.order_container_id', type='string', ui_kind='text'),
                DeclarationEntry(name='box_type', path='$.container.box_type', type='string', ui_kind='text'),
                DeclarationEntry(name='box_num', path='$.container.box_num', type='string', ui_kind='text'),
                DeclarationEntry(name='box_no', path='$.container.box_no', type='array', state='collapse'),
                DeclarationEntry(name='seal_number', path='$.container.seal_number', type='array', state='collapse'),
                DeclarationEntry(name='sea_trans_unit_price', path='$.container.sea_trans_unit_price', type='number', ui_kind='number'),
            ]),
        DeclarationEntry(name='message_board', path='$.message_board', type='array', example=[], ui_kind='json'),
        DeclarationEntry(name='customer_file_list', path='$.customer_file_list', type='array', example=[], ui_kind='json'),
        DeclarationEntry(name='supplier', path='$.supplier', type='array', example=[{'order_supplier_id': '', 'order_id': '', 'isset_supplier': '1', 'is_primary': '1', 'supplier_id': '805', 'supplier_name': '青岛雅然国际物流有限公司', 'settle_object_id': '1384', 'user_id': '336', 'user_name': '闫航', 'service_item': 'booking_space', 'supplier_period': '60', 'settlement_date': '20', 'supplier_pay_date': '0', 'is_manual': '0', 'sys_upttime': '2026-07-01 13:14:48', 'supplier_label': '青岛雅然国际物流有限公司-订舱', 'service_item_name': '订舱', 'isset_fee': False}], ui_kind='json'),
        DeclarationEntry(name='order_id', path='$.order_id', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='order_no', path='$.order_no', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='customer_category', path='$.customer_category', type='string', example=',1,2,', ui_kind='text'),
        DeclarationEntry(name='customer_tax_number', path='$.customer_tax_number', type='string', example='91370786MA3D6MW35A', ui_kind='text'),
        DeclarationEntry(name='customer_address_cn', path='$.customer_address_cn', type='string', example='山东省潍坊市昌邑市围子街道206国道北(官道郜北)', ui_kind='text'),
        DeclarationEntry(name='client_expand_id', path='$.client_expand_id', type='string', example='261', ui_kind='text'),
        DeclarationEntry(name='customer_contact_phone', path='$.customer_contact_phone', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='customer_main_id', path='$.customer_main_id', type='string', example='15', ui_kind='text'),
        DeclarationEntry(name='customer_main_name', path='$.customer_main_name', type='string', example='成都易汇瀚供应链管理有限公司', ui_kind='text'),
        DeclarationEntry(name='business_main_id', path='$.business_main_id', type='string', example='1', ui_kind='text'),
        DeclarationEntry(name='business_main_name', path='$.business_main_name', type='string', example='青岛易航道物流科技有限公司', ui_kind='text'),
        DeclarationEntry(name='fund_code', path='$.fund_code', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='fund_name', path='$.fund_name', type='string', ui_kind='text'),
        DeclarationEntry(name='track_atd', path='$.track_atd', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='track_eta', path='$.track_eta', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='track_ata', path='$.track_ata', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='track_stcs', path='$.track_stcs', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='track_ship_name', path='$.track_ship_name', type='string', ui_kind='text'),
        DeclarationEntry(name='track_voy', path='$.track_voy', type='string', ui_kind='text'),
        DeclarationEntry(name='finance_date', path='$.finance_date', type='string', example='1782316800', ui_kind='text'),
        DeclarationEntry(name='pol_cn', path='$.pol_cn', type='string', example='青岛流亭机场', ui_kind='text'),
        DeclarationEntry(name='pol_country_id', path='$.pol_country_id', type='string', example='1', ui_kind='text'),
        DeclarationEntry(name='pol_country', path='$.pol_country', type='string', example='CHINA', ui_kind='text'),
        DeclarationEntry(name='pol_country_cn', path='$.pol_country_cn', type='string', example='中国', ui_kind='text'),
        DeclarationEntry(name='pod_cn', path='$.pod_cn', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='pot_cn', path='$.pot_cn', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='del_cn', path='$.del_cn', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='country_id', path='$.country_id', type='string', example='1', ui_kind='text'),
        DeclarationEntry(name='country_name_cn', path='$.country_name_cn', type='string', example='中国', ui_kind='text'),
        DeclarationEntry(name='customer_period', path='$.customer_period', type='string', example='120', ui_kind='text'),
        DeclarationEntry(name='customer_settlement_date', path='$.customer_settlement_date', type='string', example='10', ui_kind='text'),
        DeclarationEntry(name='period_rule', path='$.period_rule', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='term_rule_name', path='$.term_rule_name', type='string', ui_kind='text'),
        DeclarationEntry(name='customer_due_date', path='$.customer_due_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='customer_put_date', path='$.customer_put_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='customer_payment_collection_date', path='$.customer_payment_collection_date', type='string', ui_kind='text'),
        DeclarationEntry(name='customer_put_date_manual', path='$.customer_put_date_manual', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='customer_put_writeoff_date', path='$.customer_put_writeoff_date', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='supplier_due_date', path='$.supplier_due_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='discount_start', path='$.discount_start', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='discount_rule', path='$.discount_rule', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='discount_end', path='$.discount_end', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='discount_ratio', path='$.discount_ratio', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='discount_status', path='$.discount_status', type='string', example='2', ui_kind='text'),
        DeclarationEntry(name='discount_currency', path='$.discount_currency', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='book_upload_date', path='$.book_upload_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='trans_cost_put_preserve_date', path='$.trans_cost_put_preserve_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='bl_no_upload_date', path='$.bl_no_upload_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='supplier_invoice_date', path='$.supplier_invoice_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='supplier_invoice_taketime', path='$.supplier_invoice_taketime', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='real_cost_date', path='$.real_cost_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='customer_invoice_request_date', path='$.customer_invoice_request_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='first_financing_doc_ok_date', path='$.first_financing_doc_ok_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='second_financing_doc_ok_date', path='$.second_financing_doc_ok_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='insurance_doc_ok_date', path='$.insurance_doc_ok_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='customer_confirm_date', path='$.customer_confirm_date', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='is_delayed_recovery', path='$.is_delayed_recovery', type='string', example='否', ui_kind='text'),
        DeclarationEntry(name='delayed_recovery_usd', path='$.delayed_recovery_usd', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='delayed_recovery_cny', path='$.delayed_recovery_cny', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='delayed_time', path='$.delayed_time', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='expect_fee_status', path='$.expect_fee_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='real_fee_status', path='$.real_fee_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='fee_lock_status', path='$.fee_lock_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='pay_account_status', path='$.pay_account_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='account_status', path='$.account_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='real_pay_usd', path='$.real_pay_usd', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='real_pay_cny', path='$.real_pay_cny', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='real_put_usd', path='$.real_put_usd', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='real_put_cny', path='$.real_put_cny', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='real_put_discount_rate', path='$.real_put_discount_rate', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='exchange_rate', path='$.exchange_rate', type='string', example='6.8067', ui_kind='text'),
        DeclarationEntry(name='folde_pay_usd', path='$.folde_pay_usd', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='folde_put_usd', path='$.folde_put_usd', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='folde_pay_total', path='$.folde_pay_total', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='folde_put_total', path='$.folde_put_total', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='gross_margin', path='$.gross_margin', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='gross_margin_rate', path='$.gross_margin_rate', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='is_special_pay', path='$.is_special_pay', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='is_loan_before_invoice', path='$.is_loan_before_invoice', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='is_fee_miss', path='$.is_fee_miss', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='fee_miss_name', path='$.fee_miss_name', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='cancel_time', path='$.cancel_time', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='effective_id', path='$.effective_id', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='effective_by', path='$.effective_by', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='effective_time', path='$.effective_time', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='create_id', path='$.create_id', type='string', example='828', ui_kind='text'),
        DeclarationEntry(name='create_by', path='$.create_by', type='string', example='GIMBAL', ui_kind='text'),
        DeclarationEntry(name='create_time', path='$.create_time', type='string', example='1782882887', ui_kind='text'),
        DeclarationEntry(name='update_id', path='$.update_id', type='string', example='828', ui_kind='text'),
        DeclarationEntry(name='update_by', path='$.update_by', type='string', example='GIMBAL', ui_kind='text'),
        DeclarationEntry(name='update_time', path='$.update_time', type='string', example='1782882935', ui_kind='text'),
        DeclarationEntry(name='delete_time', path='$.delete_time', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='business_time', path='$.business_time', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='main_ids', path='$.main_ids', type='string', example=',15,16,1,', ui_kind='text'),
        DeclarationEntry(name='reverse_status', path='$.reverse_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='proprietary_business_status', path='$.proprietary_business_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='loan_status', path='$.loan_status', type='string', ui_kind='text'),
        DeclarationEntry(name='first_status', path='$.first_status', type='string', ui_kind='text'),
        DeclarationEntry(name='second_status', path='$.second_status', type='string', ui_kind='text'),
        DeclarationEntry(name='loan_pay_status', path='$.loan_pay_status', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='change_type', path='$.change_type', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='copy_order_id', path='$.copy_order_id', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='real_fee_locked', path='$.real_fee_locked', type='boolean', example=False, ui_kind='boolean'),
        DeclarationEntry(name='is_usd_project', path='$.is_usd_project', type='string', example='2', ui_kind='text'),
        DeclarationEntry(name='pay_status', path='$.pay_status', type='string', example='1', ui_kind='text'),
        DeclarationEntry(name='is_sync_es', path='$.is_sync_es', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='expect_discount_status', path='$.expect_discount_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='real_discount_status', path='$.real_discount_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='entrust_status', path='$.entrust_status', type='string', example='2', ui_kind='text'),
        DeclarationEntry(name='audit_type', path='$.audit_type', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='is_system_generate', path='$.is_system_generate', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='is_financing', path='$.is_financing', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='confirm_status', path='$.confirm_status', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='is_traverse', path='$.is_traverse', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='financing_apply_amount', path='$.financing_apply_amount', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='financing_apply_amount_cny', path='$.financing_apply_amount_cny', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='financing_apply_amount_usd', path='$.financing_apply_amount_usd', type='string', example='0.00', ui_kind='text'),
        DeclarationEntry(name='sys_upttime', path='$.sys_upttime', type='string', example='2026-07-01 13:15:35', ui_kind='text'),
        DeclarationEntry(name='customer_put_date_desc', path='$.customer_put_date_desc', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='deposit_refund_month', path='$.deposit_refund_month', type='string', ui_kind='text'),
        DeclarationEntry(name='payment_type', path='$.payment_type', type='string', example='0', ui_kind='text'),
        DeclarationEntry(name='reverse_status_name', path='$.reverse_status_name', type='string', example='否', ui_kind='text'),
        DeclarationEntry(name='is_delayed_recovery_name', path='$.is_delayed_recovery_name', type='string', example='否', ui_kind='text'),
        DeclarationEntry(name='order_finance_arr', path='$.order_finance_arr', type='array', example=[], ui_kind='json'),
        DeclarationEntry(name='order_main_bank_arr', path='$.order_main_bank_arr', type='array', example=[], ui_kind='json'),
        DeclarationEntry(name='order_sub', path='$.order_sub', type='array', example=[], ui_kind='json'),
        DeclarationEntry(name='order_sub_no', path='$.order_sub_no', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='service_project', path='$.service_project', type='object', example={'booking_space': False, 'customs_clearance': False, 'manifest': False, 'insurance': False, 'trucking': False}, ui_kind='json'),
        DeclarationEntry(name='service_project_amount', path='$.service_project_amount', type='object', example={'booking_space': False, 'customs_clearance': False, 'manifest': False, 'insurance': False, 'trucking': False}, ui_kind='json'),
        DeclarationEntry(name='finance_status', path='$.finance_status', type='boolean', example=True, ui_kind='boolean'),
        DeclarationEntry(name='main_ids_name', path='$.main_ids_name', type='string', example='易汇瀚,易海,易航道', ui_kind='text'),
        DeclarationEntry(name='policy_main_arr', path='$.policy_main_arr', type='array', example=[{'fee_main_id': '15', 'main_name': '成都易汇瀚供应链管理有限公司'}, {'fee_main_id': '16', 'main_name': '青岛易海供应链管理有限公司'}, {'fee_main_id': '1', 'main_name': '青岛易航道物流科技有限公司'}], ui_kind='json'),
        DeclarationEntry(name='policy_type_name', path='$.policy_type_name', type='string', example='结算业务', ui_kind='text'),
        DeclarationEntry(name='business_type_name', path='$.business_type_name', type='string', example='海运整箱', ui_kind='text'),
        DeclarationEntry(name='cargo_type_name', path='$.cargo_type_name', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='period_rule_name', path='$.period_rule_name', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='trade_term_name', path='$.trade_term_name', type='string', example='CIF', ui_kind='text'),
        DeclarationEntry(name='carrier_name', path='$.carrier_name', type='string', example='中国远洋运输（集团）总公司', ui_kind='text'),
        DeclarationEntry(name='terms_transport_name', path='$.terms_transport_name', type='string', example='CY/CY', ui_kind='text'),
        DeclarationEntry(name='terms_payment_name', path='$.terms_payment_name', type='string', example='T/T', ui_kind='text'),
        DeclarationEntry(name='pay_type_name', path='$.pay_type_name', type='string', example='FREIGHT PREPAID', ui_kind='text'),
        DeclarationEntry(name='m_delivery_type_name', path='$.m_delivery_type_name', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='payment_type_name', path='$.payment_type_name', type='string', example='空', ui_kind='text'),
        DeclarationEntry(name='audit', path='$.audit', type='array', example=[], ui_kind='json'),
        DeclarationEntry(name='enable', path='$.enable', type='string', example='1', ui_kind='text'),
        DeclarationEntry(name='policy_match', path='$.policy_match', type='string', example='semi', ui_kind='text'),
        DeclarationEntry(name='policy_match_name', path='$.policy_match_name', type='string', example='手动选择', ui_kind='text'),
        DeclarationEntry(name='real_discount_status_name', path='$.real_discount_status_name', type='string', example='—', ui_kind='text'),
        DeclarationEntry(name='expect_discount_status_name', path='$.expect_discount_status_name', type='string', example='—', ui_kind='text'),
        DeclarationEntry(name='expect_policy_status_name', path='$.expect_policy_status_name', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='policy_status_name', path='$.policy_status_name', type='string', example='', ui_kind='text'),
        DeclarationEntry(name='subsidy_category_name', path='$.subsidy_category_name', type='string', example='—', ui_kind='text'),
        DeclarationEntry(name='expect_subsidy_category_name', path='$.expect_subsidy_category_name', type='string', example='—', ui_kind='text'),
        DeclarationEntry(name='real_subsidy_category_name', path='$.real_subsidy_category_name', type='string', example='—', ui_kind='text'),
        DeclarationEntry(name='action', path='$.action', type='string', example='check', ui_kind='text'),
        DeclarationEntry(name='order_file', path='$.order_file', type='array', example=[], ui_kind='json'),
        # 传递面(spec §2):备注族描述性字段 —— 值随 platform 两层值表(服务绑定+全局默认)走
        DeclarationEntry(name='remark', path='$.remark', state='carry', type='string', description='订单备注(随请求传递,不进表单)'),
        DeclarationEntry(name='notes', path='$.notes', state='carry', type='string', description='内部备注(随请求传递,不进表单)'),
        DeclarationEntry(name='cancel_remark', path='$.cancel_remark', state='carry', type='string', description='取消备注(随请求传递,不进表单)'),
        ],
        
    ),
    responses={
        200: ResponseSpec(
            status=200,
            description="成功",
        ),
    },
    version=FIN_DEFAULT_VERSION,
    metadata=EndpointMetadata(
        module=FIN_DEFAULT_MODULE,
        owner=FIN_DEFAULT_OWNER,
        tags=list(FIN_DEFAULT_TAGS),
    ),
)
