"""fin.order_entrust.order_add —— 委托订舱下单接口契约。在 scen_test_14 中出现4次。"""

from typing import Final

from gimbal_plate.systems.fin.system_info import (
    FIN_DEFAULT_AUTHOR,
    FIN_DEFAULT_MODULE,
    FIN_DEFAULT_OWNER,
    FIN_DEFAULT_PRIORITY,
    FIN_DEFAULT_TAGS,
    FIN_DEFAULT_VERSION,
    FIN_SYSTEM,
)

from gimbal_plate.schema.endpoint import (
    ApiSpec,
    EndpointSpec,
    DeclarationEntry,
    RequestSpec,
    ResponseSpec,
    EndpointMetadata,
)

# ----------------------------------------------------------------------
# 来源: curl 导入 | 生成时间: 2026-09-01T07:29:13.326038+00:00
# 人工已确认: 类型/必填/绑定面/响应语义/能力声明
# 原始 curl(认证信息已脱敏):
#   curl --url 'https://fin-tidb.21eflag.com/api/order/orderEntrust/orderAdd'    -H 'Accept: application/json, text/plain, */*'    -H 'Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7'    -H 'Authorization: ***REDACTED***'    -H 'Connection: keep-alive'    -H 'Content-Type: application/json;charset=UTF-8'    -H 'Origin: https://fin-tidb.21eflag.com'    -H 'Referer: https://fin-tidb.21eflag.com/'    -H 'Sec-Fetch-Dest: empty'    -H 'Sec-Fetch-Mode: cors'    -H 'Sec-Fetch-Site: same-origin'    -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0'    -H 'sec-ch-ua: "Not=A?Brand";v="99", "Microsoft Edge";v="151", "Chromium";v="151"'    -H 'sec-ch-ua-mobile: ?0'    -H 'sec-ch-ua-platform: "Windows"'    -b 'rememberMe=true; username=18180789650; PHPSESSID=grfb3ngdiae9pd44ihj91v8arr; think_language=zh-CN; password=iwyIYO3mqqLwnODZDxadCzUvLk9TMoJxrB/O1ubK4TAi8H0niCTrbccYl+4EHD+4h0JdPvRGPnkY/4mMY70Evw==; Admin-Token=***REDACTED***'    --data-raw '{"client_expand_name":"孙奉盛","client_expand_id":"41","m_delivery_type":"","customer_id":"335247043402399744","customer_name":"","receive_time_limit":"5","deposit_refund_day":"60","deposit_settlement_date":"30","service_id":"41","service_name":"孙奉盛","sale_id":"795","sale_name":"孙奉盛运营","operator_id":"786","operator_name":"","customer_contact_id":"335247043675029504","customer_contact_name":"","main_sort":"易航道-易汇联","policy_id":"295502731957764096","policy_name":"sfs易航道-易汇联","policy_type":"JSZX","settle_type":"1","settle_type_name":"月结","product_id":"2","product_name":"月结-延长-无保证金","deposit_type":"2","deposit_type_name":"无","period_delay_type":"1","period_delay_type_name":"延长","service_items":["booking_space"],"business_type":"1","trade_term":"","carrier":"ONE","carrier_id":"110","bl_no":"Codfish_TEST_001","track_bl_no":"Codfish_TEST_001","etd":1785945600,"atd":1786377600,"ship_name":"ONE SAN DIEGO","voy":"6275","pol":"QINGDAO,CHINA","pot":"AOSHANWEI,CHINA","pod":"FREMANTLE,AUSTRALIA","del":"FREMANTLE,AUSTRALIA","country_name":"AUSTRALIA","airline_type":"澳洲","ocean_type":"远洋","terms_payment":"T/T","terms_transport":"CY/CY","pay_type":"FREIGHT PREPAID","customer_order_sn":"","terms_shipment":"测试装运条款","shipper":"测试发货人","consignee":"测试收货人","notifier":"测试通知人","ship_mark":"测试唛头","commodity":"测试品名","notes":"测试备注","cargo_type":"goods","packer":"测试包装","num":"1","gross_weight":"1.00","bulk":"999","sea_trans_cost":"","teu":"","volume":"","volume_desc":"","order_sn":"","status":"1","sea_trans_currency":"USD","container":[],"message_board":[],"customer_file_list":[],"supplier":[{"is_manual":"","is_primary":"1","isset_fee":"0","isset_supplier":"1","order_id":"","order_supplier_id":"","service_item":"booking_space","service_item_name":"订舱","settle_object_id":"15","settlement_date":null,"pay_time_limit":"10","supplier_id":"1","supplier_name":"山东旭禾国际贸易有限公司","supplier_pay_date":null,"supplier_period":null,"user_id":"41","user_name":"孙奉盛","settle_type":"1","supplier_name_clean":"山东旭禾国际贸易有限公司","supplier_name_en":"","tax_number":"91370811MA3F04A516","settle_object":"山东旭禾国际贸易有限公司","settle_object_clean":"山东旭禾国际贸易有限公司","settle_type_name":"月结"}],"remark":"","payment_type_name":"确定性付款","payment_type":"1","policy_type_name":"","main_ids":"1,3","pot_cn":null,"pot_port_name":"AOSHANWEI,CHINA","pol_cn":"青岛港","pol_port_name":"QINGDAO,CHINA","pol_country_id":"1","pol_country":"CHINA","pol_country_cn":"中国","del_cn":"弗里曼特尔","del_port_name":"FREMANTLE,AUSTRALIA","pod_cn":"弗里曼特尔","pod_port_name":"FREMANTLE,AUSTRALIA","country_id":"673","country_name_cn":"澳大利亚","entrust_status":1,"order_file":[]}'
# ----------------------------------------------------------------------
ORDER_ENTRUST_ORDER_CONFIRM: Final[EndpointSpec] = EndpointSpec(
    id='fin.order_entrust.order_confirm',
    system='fin',
    service='fin-service',
    name='委托订单确认',
    description='委托订单确认',
    api=ApiSpec(
        service='fin-service',
        method='POST',
        path='/api/order/orderEntrust/orderAdd',
        headers={},
        consumes=[],
        produces=[],
    ),
    request=RequestSpec(
        body_type='json',
        
        declarations=[
            DeclarationEntry(name='bl_no', path='$.bl_no', type='string', example='Codfish-IPKZ-Test', ui_kind='text'),
            DeclarationEntry(name='order_id', path='$.order_id', type='string', default='354066893969032192', example='354066893969032192', ui_kind='text'),
            DeclarationEntry(name='order_no', path='$.order_no', type='string', default='YWDD20260904110854', example='YWDD20260904110854', ui_kind='text'),
            DeclarationEntry(name='track_bl_no', path='$.track_bl_no', type='string', example='Codfish-IPKZ-Test', ui_kind='text'),
            DeclarationEntry(name='entrust_status', path='$.entrust_status', type='string', default='2', example='2', ui_kind='text'),
            DeclarationEntry(name='action', path='$.action', type='string', default='check', example='check', ui_kind='text'),
            DeclarationEntry(name='customer_file_list', path='$.customer_file_list', type='array', example=[{"client_company_id": "335247043402399744","client_company_name": "绍兴柯桥鹏达进出口有限公司","trustee_company_id": "1","trustee_company_name": "青岛易航道物流科技有限公司","document_type": "BOOK_CUSTOMER","file_url": "6a9a8954ca71a.pdf","file_name": "6a9a8954ca71a.pdf","file_id": "354189666712290304","file_type": "PDF","_XID": "row_3248"}], ui_kind='text'),
            # 传递面(carry 通道,不进表单,值随 platform 两层值表走)
            DeclarationEntry(name='order_file', path='$.order_file', state='carry', type='string'),
            DeclarationEntry(name='client_expand_name', path='$.client_expand_name', state='carry', type='string'),
            DeclarationEntry(name='m_delivery_type', path='$.m_delivery_type', state='carry', type='string'),
            DeclarationEntry(name='customer_id', path='$.customer_id', state='carry', type='string'),
            DeclarationEntry(name='customer_name', path='$.customer_name', state='carry', type='string'),
            DeclarationEntry(name='service_id', path='$.service_id', state='carry', type='string'),
            DeclarationEntry(name='service_name', path='$.service_name', state='carry', type='string'),
            DeclarationEntry(name='sale_id', path='$.sale_id', state='carry', type='string'),
            DeclarationEntry(name='sale_name', path='$.sale_name', state='carry', type='string'),
            DeclarationEntry(name='operator_id', path='$.operator_id', state='carry', type='string'),
            DeclarationEntry(name='operator_name', path='$.operator_name', state='carry', type='string'),
            DeclarationEntry(name='customer_contact_id', path='$.customer_contact_id', state='carry', type='string'),
            DeclarationEntry(name='customer_contact_name', path='$.customer_contact_name', state='carry', type='string'),
            DeclarationEntry(name='main_sort', path='$.main_sort', state='carry', type='string'),
            DeclarationEntry(name='policy_id', path='$.policy_id', state='carry', type='string'),
            DeclarationEntry(name='policy_name', path='$.policy_name', state='carry', type='string'),
            DeclarationEntry(name='policy_type', path='$.policy_type', state='carry', type='string'),
            DeclarationEntry(name='settle_type', path='$.settle_type', state='carry', type='string'),
            DeclarationEntry(name='settle_type_name', path='$.settle_type_name', state='carry', type='string'),
            DeclarationEntry(name='customer_product_id', path='$.customer_product_id', state='carry', type='string'),
            DeclarationEntry(name='product_name', path='$.product_name', state='carry', type='string'),
            DeclarationEntry(name='deposit_type', path='$.deposit_type', state='carry', type='string'),
            DeclarationEntry(name='deposit_type_name', path='$.deposit_type_name', state='carry', type='string'),
            DeclarationEntry(name='period_delay_type', path='$.period_delay_type', state='carry', type='string'),
            DeclarationEntry(name='period_delay_type_name', path='$.period_delay_type_name', state='carry', type='string'),
            DeclarationEntry(name='service_items', path='$.service_items', state='carry', type='array'),
            DeclarationEntry(name='business_type', path='$.business_type', state='carry', type='string'),
            DeclarationEntry(name='trade_term', path='$.trade_term', state='carry', type='string'),
            DeclarationEntry(name='carrier', path='$.carrier', state='carry', type='string'),
            DeclarationEntry(name='carrier_id', path='$.carrier_id', state='carry', type='string'),
            DeclarationEntry(name='etd', path='$.etd', state='carry', type='integer'),
            DeclarationEntry(name='atd', path='$.atd', state='carry', type='integer'),
            DeclarationEntry(name='ship_name', path='$.ship_name', state='carry', type='string'),
            DeclarationEntry(name='voy', path='$.voy', state='carry', type='string'),
            DeclarationEntry(name='pol', path='$.pol', state='carry', type='string'),
            DeclarationEntry(name='pot', path='$.pot', state='carry', type='string'),
            DeclarationEntry(name='pod', path='$.pod', state='carry', type='string'),
            DeclarationEntry(name='del', path='$.del', state='carry', type='string'),
            DeclarationEntry(name='country_name', path='$.country_name', state='carry', type='string'),
            DeclarationEntry(name='airline_type', path='$.airline_type', state='carry', type='string'),
            DeclarationEntry(name='ocean_type', path='$.ocean_type', state='carry', type='string'),
            DeclarationEntry(name='terms_payment', path='$.terms_payment', state='carry', type='string'),
            DeclarationEntry(name='terms_transport', path='$.terms_transport', state='carry', type='string'),
            DeclarationEntry(name='pay_type', path='$.pay_type', state='carry', type='string'),
            DeclarationEntry(name='customer_order_sn', path='$.customer_order_sn', state='carry', type='string'),
            DeclarationEntry(name='terms_shipment', path='$.terms_shipment', state='carry', type='string'),
            DeclarationEntry(name='shipper', path='$.shipper', state='carry', type='string'),
            DeclarationEntry(name='consignee', path='$.consignee', state='carry', type='string'),
            DeclarationEntry(name='notifier', path='$.notifier', state='carry', type='string'),
            DeclarationEntry(name='ship_mark', path='$.ship_mark', state='carry', type='string'),
            DeclarationEntry(name='commodity', path='$.commodity', state='carry', type='string'),
            DeclarationEntry(name='notes', path='$.notes', state='carry', type='string'),
            DeclarationEntry(name='cargo_type', path='$.cargo_type', state='carry', type='string'),
            DeclarationEntry(name='packer', path='$.packer', state='carry', type='string'),
            DeclarationEntry(name='num', path='$.num', state='carry', type='string'),
            DeclarationEntry(name='gross_weight', path='$.gross_weight', state='carry', type='string'),
            DeclarationEntry(name='bulk', path='$.bulk', state='carry', type='string'),
            DeclarationEntry(name='sea_trans_cost', path='$.sea_trans_cost', state='carry', type='string'),
            DeclarationEntry(name='teu', path='$.teu', state='carry', type='string'),
            DeclarationEntry(name='volume', path='$.volume', state='carry', type='string'),
            DeclarationEntry(name='volume_desc', path='$.volume_desc', state='carry', type='string'),
            DeclarationEntry(name='order_sn', path='$.order_sn', state='carry', type='string'),
            DeclarationEntry(name='status', path='$.status', state='carry', type='integer'),
            DeclarationEntry(name='sea_trans_currency', path='$.sea_trans_currency', state='carry', type='string'),
            DeclarationEntry(name='message_board', path='$.message_board', state='carry', type='array'),
            # 2026-09-05 缩并:原 $.supplier[0].* / $.container[0].* binding 深实例叶子
            # 并入容器模板 children。盖戳分流:$.supplier 在 HEAD 已是 carry 容器
            # (旧 855 行)→ 整传一致性子孙 carry;$.container HEAD 无容器条目、
            # 仅 binding 深叶 → binding→form(切换面等价,§6-M3 ⑧ 对拍修正)
            # 同日补全:container 行形状三方印证(order_add example /
            # order_customer_container curl / Scenario_Test_14 转储)补齐 5 键,
            # 行内业务键回到树行组渲染,不再落「其他字段」;不带 default/example
            # → platform 导出 D7 深层无值不落 None 骨架,body 零漂移
            DeclarationEntry(name='supplier', path='$.supplier', state='carry', type='array',
                children=[
                    DeclarationEntry(name='supplier_id', path='$.supplier.order_supplier_id', state='carry', type='string'),
                    DeclarationEntry(name='supplier_order_id', path='$.supplier.order_id', state='carry', type='string'),
                ]),
            DeclarationEntry(name='container', path='$.container', state='form', type='array',
                children=[
                    DeclarationEntry(name='order_container_id', path='$.container.order_container_id', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='box_type', path='$.container.box_type', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='box_num', path='$.container.box_num', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='box_no', path='$.container.box_no', state='form', type='array'),
                    DeclarationEntry(name='seal_number', path='$.container.seal_number', state='form', type='array'),
                    DeclarationEntry(name='sea_trans_unit_price', path='$.container.sea_trans_unit_price', state='form', type='number', ui_kind='number'),
                ]),
            DeclarationEntry(name='customer_category', path='$.customer_category', state='carry', type='string'),
            DeclarationEntry(name='customer_tax_number', path='$.customer_tax_number', state='carry', type='string'),
            DeclarationEntry(name='customer_address_cn', path='$.customer_address_cn', state='carry', type='string'),
            DeclarationEntry(name='client_expand_id', path='$.client_expand_id', state='carry', type='string'),
            DeclarationEntry(name='customer_contact_phone', path='$.customer_contact_phone', state='carry', type='string'),
            DeclarationEntry(name='customer_main_id', path='$.customer_main_id', state='carry', type='string'),
            DeclarationEntry(name='customer_main_name', path='$.customer_main_name', state='carry', type='string'),
            DeclarationEntry(name='business_main_id', path='$.business_main_id', state='carry', type='string'),
            DeclarationEntry(name='business_main_name', path='$.business_main_name', state='carry', type='string'),
            DeclarationEntry(name='fund_code', path='$.fund_code', state='carry', type='string'),
            DeclarationEntry(name='fund_name', path='$.fund_name', state='carry', type='string'),
            DeclarationEntry(name='track_atd', path='$.track_atd', state='carry', type='string'),
            DeclarationEntry(name='track_eta', path='$.track_eta', state='carry', type='string'),
            DeclarationEntry(name='track_ata', path='$.track_ata', state='carry', type='string'),
            DeclarationEntry(name='track_stcs', path='$.track_stcs', state='carry', type='string'),
            DeclarationEntry(name='track_ship_name', path='$.track_ship_name', state='carry', type='string'),
            DeclarationEntry(name='track_voy', path='$.track_voy', state='carry', type='string'),
            DeclarationEntry(name='finance_date', path='$.finance_date', state='carry', type='string'),
            DeclarationEntry(name='pol_cn', path='$.pol_cn', state='carry', type='string'),
            DeclarationEntry(name='pol_country_id', path='$.pol_country_id', state='carry', type='string'),
            DeclarationEntry(name='pol_country', path='$.pol_country', state='carry', type='string'),
            DeclarationEntry(name='pol_country_cn', path='$.pol_country_cn', state='carry', type='string'),
            DeclarationEntry(name='pod_cn', path='$.pod_cn', state='carry', type='string'),
            DeclarationEntry(name='pot_cn', path='$.pot_cn', state='carry', type='string'),
            DeclarationEntry(name='del_cn', path='$.del_cn', state='carry', type='string'),
            DeclarationEntry(name='country_id', path='$.country_id', state='carry', type='string'),
            DeclarationEntry(name='country_name_cn', path='$.country_name_cn', state='carry', type='string'),
            DeclarationEntry(name='customer_period', path='$.customer_period', state='carry', type='string'),
            DeclarationEntry(name='customer_settlement_date', path='$.customer_settlement_date', state='carry', type='string'),
            DeclarationEntry(name='period_rule', path='$.period_rule', state='carry', type='string'),
            DeclarationEntry(name='term_rule_name', path='$.term_rule_name', state='carry', type='string'),
            DeclarationEntry(name='customer_due_date', path='$.customer_due_date', state='carry', type='string'),
            DeclarationEntry(name='customer_put_date', path='$.customer_put_date', state='carry', type='string'),
            DeclarationEntry(name='customer_payment_collection_date', path='$.customer_payment_collection_date', state='carry', type='string'),
            DeclarationEntry(name='customer_put_date_manual', path='$.customer_put_date_manual', state='carry', type='string'),
            DeclarationEntry(name='customer_put_writeoff_date', path='$.customer_put_writeoff_date', state='carry', type='string'),
            DeclarationEntry(name='supplier_due_date', path='$.supplier_due_date', state='carry', type='string'),
            DeclarationEntry(name='discount_start', path='$.discount_start', state='carry', type='string'),
            DeclarationEntry(name='discount_rule', path='$.discount_rule', state='carry', type='string'),
            DeclarationEntry(name='discount_end', path='$.discount_end', state='carry', type='string'),
            DeclarationEntry(name='discount_ratio', path='$.discount_ratio', state='carry', type='string'),
            DeclarationEntry(name='discount_status', path='$.discount_status', state='carry', type='string'),
            DeclarationEntry(name='discount_currency', path='$.discount_currency', state='carry', type='string'),
            DeclarationEntry(name='book_upload_date', path='$.book_upload_date', state='carry', type='string'),
            DeclarationEntry(name='trans_cost_put_preserve_date', path='$.trans_cost_put_preserve_date', state='carry', type='string'),
            DeclarationEntry(name='bl_no_upload_date', path='$.bl_no_upload_date', state='carry', type='string'),
            DeclarationEntry(name='supplier_invoice_date', path='$.supplier_invoice_date', state='carry', type='string'),
            DeclarationEntry(name='supplier_invoice_taketime', path='$.supplier_invoice_taketime', state='carry', type='string'),
            DeclarationEntry(name='real_cost_date', path='$.real_cost_date', state='carry', type='string'),
            DeclarationEntry(name='customer_invoice_request_date', path='$.customer_invoice_request_date', state='carry', type='string'),
            DeclarationEntry(name='first_financing_doc_ok_date', path='$.first_financing_doc_ok_date', state='carry', type='string'),
            DeclarationEntry(name='second_financing_doc_ok_date', path='$.second_financing_doc_ok_date', state='carry', type='string'),
            DeclarationEntry(name='insurance_doc_ok_date', path='$.insurance_doc_ok_date', state='carry', type='string'),
            DeclarationEntry(name='customer_confirm_date', path='$.customer_confirm_date', state='carry', type='string'),
            DeclarationEntry(name='is_delayed_recovery', path='$.is_delayed_recovery', state='carry', type='string'),
            DeclarationEntry(name='delayed_recovery_usd', path='$.delayed_recovery_usd', state='carry', type='string'),
            DeclarationEntry(name='delayed_recovery_cny', path='$.delayed_recovery_cny', state='carry', type='string'),
            DeclarationEntry(name='delayed_time', path='$.delayed_time', state='carry', type='string'),
            DeclarationEntry(name='expect_fee_status', path='$.expect_fee_status', state='carry', type='string'),
            DeclarationEntry(name='real_fee_status', path='$.real_fee_status', state='carry', type='string'),
            DeclarationEntry(name='fee_lock_status', path='$.fee_lock_status', state='carry', type='string'),
            DeclarationEntry(name='pay_account_status', path='$.pay_account_status', state='carry', type='string'),
            DeclarationEntry(name='account_status', path='$.account_status', state='carry', type='string'),
            DeclarationEntry(name='real_pay_usd', path='$.real_pay_usd', state='carry', type='string'),
            DeclarationEntry(name='real_pay_cny', path='$.real_pay_cny', state='carry', type='string'),
            DeclarationEntry(name='real_put_usd', path='$.real_put_usd', state='carry', type='string'),
            DeclarationEntry(name='real_put_cny', path='$.real_put_cny', state='carry', type='string'),
            DeclarationEntry(name='real_put_discount_rate', path='$.real_put_discount_rate', state='carry', type='string'),
            DeclarationEntry(name='exchange_rate', path='$.exchange_rate', state='carry', type='string'),
            DeclarationEntry(name='folde_pay_usd', path='$.folde_pay_usd', state='carry', type='string'),
            DeclarationEntry(name='folde_put_usd', path='$.folde_put_usd', state='carry', type='string'),
            DeclarationEntry(name='folde_pay_total', path='$.folde_pay_total', state='carry', type='string'),
            DeclarationEntry(name='folde_put_total', path='$.folde_put_total', state='carry', type='string'),
            DeclarationEntry(name='gross_margin', path='$.gross_margin', state='carry', type='string'),
            DeclarationEntry(name='gross_margin_rate', path='$.gross_margin_rate', state='carry', type='string'),
            DeclarationEntry(name='is_special_pay', path='$.is_special_pay', state='carry', type='string'),
            DeclarationEntry(name='is_loan_before_invoice', path='$.is_loan_before_invoice', state='carry', type='string'),
            DeclarationEntry(name='is_fee_miss', path='$.is_fee_miss', state='carry', type='string'),
            DeclarationEntry(name='fee_miss_name', path='$.fee_miss_name', state='carry', type='string'),
            DeclarationEntry(name='cancel_remark', path='$.cancel_remark', state='carry', type='string'),
            DeclarationEntry(name='cancel_time', path='$.cancel_time', state='carry', type='string'),
            DeclarationEntry(name='effective_id', path='$.effective_id', state='carry', type='string'),
            DeclarationEntry(name='effective_by', path='$.effective_by', state='carry', type='string'),
            DeclarationEntry(name='effective_time', path='$.effective_time', state='carry', type='string'),
            DeclarationEntry(name='create_id', path='$.create_id', state='carry', type='string'),
            DeclarationEntry(name='create_by', path='$.create_by', state='carry', type='string'),
            DeclarationEntry(name='create_time', path='$.create_time', state='carry', type='string'),
            DeclarationEntry(name='update_id', path='$.update_id', state='carry', type='string'),
            DeclarationEntry(name='update_by', path='$.update_by', state='carry', type='string'),
            DeclarationEntry(name='update_time', path='$.update_time', state='carry', type='string'),
            DeclarationEntry(name='delete_time', path='$.delete_time', state='carry', type='string'),
            DeclarationEntry(name='business_time', path='$.business_time', state='carry', type='string'),
            DeclarationEntry(name='main_ids', path='$.main_ids', state='carry', type='string'),
            DeclarationEntry(name='reverse_status', path='$.reverse_status', state='carry', type='string'),
            DeclarationEntry(name='proprietary_business_status', path='$.proprietary_business_status', state='carry', type='string'),
            DeclarationEntry(name='loan_status', path='$.loan_status', state='carry', type='string'),
            DeclarationEntry(name='first_status', path='$.first_status', state='carry', type='string'),
            DeclarationEntry(name='second_status', path='$.second_status', state='carry', type='string'),
            DeclarationEntry(name='loan_pay_status', path='$.loan_pay_status', state='carry', type='string'),
            DeclarationEntry(name='change_type', path='$.change_type', state='carry', type='string'),
            DeclarationEntry(name='copy_order_id', path='$.copy_order_id', state='carry', type='string'),
            DeclarationEntry(name='real_fee_locked', path='$.real_fee_locked', state='carry', type='boolean'),
            DeclarationEntry(name='is_usd_project', path='$.is_usd_project', state='carry', type='string'),
            DeclarationEntry(name='pay_status', path='$.pay_status', state='carry', type='string'),
            DeclarationEntry(name='is_sync_es', path='$.is_sync_es', state='carry', type='string'),
            DeclarationEntry(name='expect_discount_status', path='$.expect_discount_status', state='carry', type='string'),
            DeclarationEntry(name='real_discount_status', path='$.real_discount_status', state='carry', type='string'),
            DeclarationEntry(name='remark', path='$.remark', state='carry', type='string'),
            DeclarationEntry(name='audit_type', path='$.audit_type', state='carry', type='string'),
            DeclarationEntry(name='is_system_generate', path='$.is_system_generate', state='carry', type='string'),
            DeclarationEntry(name='is_financing', path='$.is_financing', state='carry', type='string'),
            DeclarationEntry(name='confirm_status', path='$.confirm_status', state='carry', type='string'),
            DeclarationEntry(name='is_traverse', path='$.is_traverse', state='carry', type='string'),
            DeclarationEntry(name='financing_apply_amount', path='$.financing_apply_amount', state='carry', type='string'),
            DeclarationEntry(name='financing_apply_amount_cny', path='$.financing_apply_amount_cny', state='carry', type='string'),
            DeclarationEntry(name='financing_apply_amount_usd', path='$.financing_apply_amount_usd', state='carry', type='string'),
            DeclarationEntry(name='sys_upttime', path='$.sys_upttime', state='carry', type='string'),
            DeclarationEntry(name='receive_time_limit', path='$.receive_time_limit', state='carry', type='string'),
            DeclarationEntry(name='customer_put_date_desc', path='$.customer_put_date_desc', state='carry', type='string'),
            DeclarationEntry(name='deposit_refund_day', path='$.deposit_refund_day', state='carry', type='string'),
            DeclarationEntry(name='deposit_settlement_date', path='$.deposit_settlement_date', state='carry', type='string'),
            DeclarationEntry(name='deposit_refund_month', path='$.deposit_refund_month', state='carry', type='string'),
            DeclarationEntry(name='payment_type', path='$.payment_type', state='carry', type='string'),
            DeclarationEntry(name='product_id', path='$.product_id', state='carry', type='string'),
            DeclarationEntry(name='revoke_status', path='$.revoke_status', state='carry', type='string'),
            DeclarationEntry(name='revoke_type', path='$.revoke_type', state='carry', type='string'),
            DeclarationEntry(name='asset_status', path='$.asset_status', state='carry', type='string'),
            DeclarationEntry(name='revoke_failure_reason', path='$.revoke_failure_reason', state='carry', type='string'),
            DeclarationEntry(name='repayment_date', path='$.repayment_date', state='carry', type='string'),
            DeclarationEntry(name='repay_warn_time', path='$.repay_warn_time', state='carry', type='string'),
            DeclarationEntry(name='reverse_status_name', path='$.reverse_status_name', state='carry', type='string'),
            DeclarationEntry(name='is_delayed_recovery_name', path='$.is_delayed_recovery_name', state='carry', type='string'),
            DeclarationEntry(name='order_finance_arr', path='$.order_finance_arr', state='carry', type='array'),
            DeclarationEntry(name='order_main_bank_arr', path='$.order_main_bank_arr', state='carry', type='array'),
            DeclarationEntry(name='order_sub', path='$.order_sub', state='carry', type='array'),
            DeclarationEntry(name='order_sub_no', path='$.order_sub_no', state='carry', type='string'),
            DeclarationEntry(name='service_project', path='$.service_project', state='carry', type='object'),
            DeclarationEntry(name='service_project_amount', path='$.service_project_amount', state='carry', type='object'),
            DeclarationEntry(name='finance_status', path='$.finance_status', state='carry', type='boolean'),
            DeclarationEntry(name='main_ids_name', path='$.main_ids_name', state='carry', type='string'),
            DeclarationEntry(name='policy_main_arr', path='$.policy_main_arr', state='carry', type='array'),
            DeclarationEntry(name='policy_type_name', path='$.policy_type_name', state='carry', type='string'),
            DeclarationEntry(name='business_type_name', path='$.business_type_name', state='carry', type='string'),
            DeclarationEntry(name='cargo_type_name', path='$.cargo_type_name', state='carry', type='string'),
            DeclarationEntry(name='period_rule_name', path='$.period_rule_name', state='carry', type='string'),
            DeclarationEntry(name='trade_term_name', path='$.trade_term_name', state='carry', type='string'),
            DeclarationEntry(name='carrier_name', path='$.carrier_name', state='carry', type='string'),
            DeclarationEntry(name='terms_transport_name', path='$.terms_transport_name', state='carry', type='string'),
            DeclarationEntry(name='terms_payment_name', path='$.terms_payment_name', state='carry', type='string'),
            DeclarationEntry(name='pay_type_name', path='$.pay_type_name', state='carry', type='string'),
            DeclarationEntry(name='m_delivery_type_name', path='$.m_delivery_type_name', state='carry', type='string'),
            DeclarationEntry(name='payment_type_name', path='$.payment_type_name', state='carry', type='string'),
            DeclarationEntry(name='audit', path='$.audit', state='carry', type='array'),
            DeclarationEntry(name='enable', path='$.enable', state='carry', type='string'),
            DeclarationEntry(name='policy_match', path='$.policy_match', state='carry', type='string'),
            DeclarationEntry(name='policy_match_name', path='$.policy_match_name', state='carry', type='string'),
            DeclarationEntry(name='real_discount_status_name', path='$.real_discount_status_name', state='carry', type='string'),
            DeclarationEntry(name='expect_discount_status_name', path='$.expect_discount_status_name', state='carry', type='string'),
            DeclarationEntry(name='expect_policy_status_name', path='$.expect_policy_status_name', state='carry', type='string'),
            DeclarationEntry(name='policy_status_name', path='$.policy_status_name', state='carry', type='string'),
            DeclarationEntry(name='subsidy_category_name', path='$.subsidy_category_name', state='carry', type='string'),
            DeclarationEntry(name='expect_subsidy_category_name', path='$.expect_subsidy_category_name', state='carry', type='string'),
            DeclarationEntry(name='real_subsidy_category_name', path='$.real_subsidy_category_name', state='carry', type='string'),
            DeclarationEntry(name='revoke_status_name', path='$.revoke_status_name', state='carry', type='string'),
            DeclarationEntry(name='revoke_type_name', path='$.revoke_type_name', state='carry', type='string'),
            DeclarationEntry(name='asset_status_name', path='$.asset_status_name', state='carry', type='string'),
        ],
    ),
    responses={
        200: ResponseSpec(
            status=200,
        ),
    },   
    version=FIN_DEFAULT_VERSION,
    metadata=EndpointMetadata(
        module=FIN_DEFAULT_MODULE,
        owner=FIN_DEFAULT_OWNER,
        tags=list(FIN_DEFAULT_TAGS),
    ),
)
