"""fin.order.order_add —— 委托订舱下单接口契约。在 scen_test_14 中出现2次。"""
from gimbal_plate.schema.endpoint import (
    ApiSpec,
    EndpointSpec,
    IOFieldBinding,
    RequestSpec,
    ResponseSpec,
)


ORDER_ORDER_ADD = EndpointSpec(
    id="fin.order.order_add",
    system="fin",
    service="order",
    name="委托订舱下单",
    description="由 Scenario_Test_14 提取: 委托订舱下单",
    api=ApiSpec(service="order", method="POST", path="/api/order/order/orderAdd", auth="bearer", timeout_seconds=30.0),
    request=RequestSpec(
        body_type="json",
        fields=[
        IOFieldBinding(name='client_expand_name', path='client_expand_name', required=True, example='唐欣雨', ui_kind='text'),
        IOFieldBinding(name='m_delivery_type', path='m_delivery_type', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='customer_id', path='customer_id', required=True, example='320', ui_kind='text'),
        IOFieldBinding(name='customer_name', path='customer_name', required=True, example='山东悦慕食品有限公司', ui_kind='text'),
        IOFieldBinding(name='receive_time_limit', path='receive_time_limit', required=True, example='20', ui_kind='text'),
        IOFieldBinding(name='deposit_refund_day', path='deposit_refund_day', required=True, example='180', ui_kind='text'),
        IOFieldBinding(name='deposit_settlement_date', path='deposit_settlement_date', required=True, example='30', ui_kind='text'),
        IOFieldBinding(name='service_id', path='service_id', required=True, example='55', ui_kind='text'),
        IOFieldBinding(name='service_name', path='service_name', required=True, example='曲静霞', ui_kind='text'),
        IOFieldBinding(name='operator_id', path='operator_id', required=True, example='336', ui_kind='text'),
        IOFieldBinding(name='operator_name', path='operator_name', required=True, example='闫航', ui_kind='text'),
        IOFieldBinding(name='customer_contact_id', path='customer_contact_id', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='customer_contact_name', path='customer_contact_name', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='main_sort', path='main_sort', required=True, example='易汇瀚,易海,易航道', ui_kind='text'),
        IOFieldBinding(name='policy_id', path='policy_id', required=True, example='134', ui_kind='text'),
        IOFieldBinding(name='policy_name', path='policy_name', required=True, example='【SPV对客】易汇瀚（仅人民币）', ui_kind='text'),
        IOFieldBinding(name='policy_type', path='policy_type', required=True, example='JSZX', ui_kind='text'),
        IOFieldBinding(name='settle_type', path='settle_type', required=True, example='1', ui_kind='text'),
        IOFieldBinding(name='settle_type_name', path='settle_type_name', required=True, example='月结', ui_kind='text'),
        IOFieldBinding(name='product_id', path='product_id', required=True, example='4', ui_kind='text'),
        IOFieldBinding(name='product_name', path='product_name', required=True, example='月结-延长-保证金', ui_kind='text'),
        IOFieldBinding(name='deposit_type', path='deposit_type', required=True, example='1', ui_kind='text'),
        IOFieldBinding(name='deposit_type_name', path='deposit_type_name', required=True, example='有', ui_kind='text'),
        IOFieldBinding(name='period_delay_type', path='period_delay_type', required=True, example='1', ui_kind='text'),
        IOFieldBinding(name='period_delay_type_name', path='period_delay_type_name', required=True, example='延长', ui_kind='text'),
        IOFieldBinding(name='service_items', path='service_items', required=True, example=['booking_space'], ui_kind='json'),
        IOFieldBinding(name='business_type', path='business_type', required=True, example='1', ui_kind='text'),
        IOFieldBinding(name='trade_term', path='trade_term', required=True, example='CIF', ui_kind='text'),
        IOFieldBinding(name='carrier', path='carrier', required=True, example='COSCO', ui_kind='text'),
        IOFieldBinding(name='carrier_id', path='carrier_id', required=True, example='16', ui_kind='text'),
        IOFieldBinding(name='bl_no', path='bl_no', required=True, example='${var.bl_no}', ui_kind='text'),
        IOFieldBinding(name='track_bl_no', path='track_bl_no', required=True, example='${var.bl_no}', ui_kind='text'),
        IOFieldBinding(name='etd', path='etd', required=True, example=1782316800, ui_kind='number'),
        IOFieldBinding(name='atd', path='atd', required=True, example=1782835200, ui_kind='number'),
        IOFieldBinding(name='ship_name', path='ship_name', required=True, example='OOCL FRANCE', ui_kind='text'),
        IOFieldBinding(name='voy', path='voy', required=True, example='068E', ui_kind='text'),
        IOFieldBinding(name='pol', path='pol', required=True, example='QINGDAO,CHINA', ui_kind='text'),
        IOFieldBinding(name='pot', path='pot', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='pod', path='pod', required=True, example='ANTING,CHINA', ui_kind='text'),
        IOFieldBinding(name='del', path='del', required=True, example='ANTING,CHINA', ui_kind='text'),
        IOFieldBinding(name='country_name', path='country_name', required=True, example='CHINA', ui_kind='text'),
        IOFieldBinding(name='airline_type', path='airline_type', required=True, example='中国', ui_kind='text'),
        IOFieldBinding(name='ocean_type', path='ocean_type', required=True, example='近洋', ui_kind='text'),
        IOFieldBinding(name='terms_payment', path='terms_payment', required=True, example='T/T', ui_kind='text'),
        IOFieldBinding(name='terms_transport', path='terms_transport', required=True, example='CY/CY', ui_kind='text'),
        IOFieldBinding(name='pay_type', path='pay_type', required=True, example='FREIGHT PREPAID', ui_kind='text'),
        IOFieldBinding(name='customer_order_sn', path='customer_order_sn', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='terms_shipment', path='terms_shipment', required=True, example='Codfish', ui_kind='text'),
        IOFieldBinding(name='shipper', path='shipper', required=True, example='Codfish', ui_kind='text'),
        IOFieldBinding(name='consignee', path='consignee', required=True, example='Codfish', ui_kind='text'),
        IOFieldBinding(name='notifier', path='notifier', required=True, example='Codfish', ui_kind='text'),
        IOFieldBinding(name='ship_mark', path='ship_mark', required=True, example='Codfish', ui_kind='text'),
        IOFieldBinding(name='commodity', path='commodity', required=True, example='Codfish', ui_kind='text'),
        IOFieldBinding(name='notes', path='notes', required=True, example='Codfish', ui_kind='text'),
        IOFieldBinding(name='cargo_type', path='cargo_type', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='packer', path='packer', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='num', path='num', required=True, example='1872', ui_kind='text'),
        IOFieldBinding(name='gross_weight', path='gross_weight', required=True, example='26800.000', ui_kind='text'),
        IOFieldBinding(name='bulk', path='bulk', required=True, example='60.000', ui_kind='text'),
        IOFieldBinding(name='sea_trans_cost', path='sea_trans_cost', required=True, example='1.00', ui_kind='text'),
        IOFieldBinding(name='teu', path='teu', required=True, example='2', ui_kind='text'),
        IOFieldBinding(name='volume', path='volume', required=True, example='1*40HQ', ui_kind='text'),
        IOFieldBinding(name='volume_desc', path='volume_desc', required=True, example='普柜', ui_kind='text'),
        IOFieldBinding(name='order_sn', path='order_sn', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='status', path='status', required=True, example=2, ui_kind='number'),
        IOFieldBinding(name='sea_trans_currency', path='sea_trans_currency', required=True, example='USD', ui_kind='text'),
        IOFieldBinding(name='container', path='container', required=True, example=[{'order_container_id': '', 'box_type': '40HQ', 'box_num': '1', 'box_no': [''], 'seal_number': [''], 'sea_trans_unit_price': 1}], ui_kind='json'),
        IOFieldBinding(name='message_board', path='message_board', required=True, example=[], ui_kind='json'),
        IOFieldBinding(name='customer_file_list', path='customer_file_list', required=True, example=[], ui_kind='json'),
        IOFieldBinding(name='supplier', path='supplier', required=True, example=[{'order_supplier_id': '', 'order_id': '', 'isset_supplier': '1', 'is_primary': '1', 'supplier_id': '805', 'supplier_name': '青岛雅然国际物流有限公司', 'settle_object_id': '1384', 'user_id': '336', 'user_name': '闫航', 'service_item': 'booking_space', 'supplier_period': '60', 'settlement_date': '20', 'supplier_pay_date': '0', 'is_manual': '0', 'sys_upttime': '2026-07-01 13:14:48', 'supplier_label': '青岛雅然国际物流有限公司-订舱', 'service_item_name': '订舱', 'isset_fee': False}], ui_kind='json'),
        IOFieldBinding(name='order_id', path='order_id', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='order_no', path='order_no', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='customer_category', path='customer_category', required=True, example=',1,2,', ui_kind='text'),
        IOFieldBinding(name='customer_tax_number', path='customer_tax_number', required=True, example='91370786MA3D6MW35A', ui_kind='text'),
        IOFieldBinding(name='customer_address_cn', path='customer_address_cn', required=True, example='山东省潍坊市昌邑市围子街道206国道北(官道郜北)', ui_kind='text'),
        IOFieldBinding(name='client_expand_id', path='client_expand_id', required=True, example='261', ui_kind='text'),
        IOFieldBinding(name='customer_contact_phone', path='customer_contact_phone', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='customer_main_id', path='customer_main_id', required=True, example='15', ui_kind='text'),
        IOFieldBinding(name='customer_main_name', path='customer_main_name', required=True, example='成都易汇瀚供应链管理有限公司', ui_kind='text'),
        IOFieldBinding(name='business_main_id', path='business_main_id', required=True, example='1', ui_kind='text'),
        IOFieldBinding(name='business_main_name', path='business_main_name', required=True, example='青岛易航道物流科技有限公司', ui_kind='text'),
        IOFieldBinding(name='fund_code', path='fund_code', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='fund_name', path='fund_name', required=True, example=None, ui_kind='text'),
        IOFieldBinding(name='track_atd', path='track_atd', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='track_eta', path='track_eta', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='track_ata', path='track_ata', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='track_stcs', path='track_stcs', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='track_ship_name', path='track_ship_name', required=True, example=None, ui_kind='text'),
        IOFieldBinding(name='track_voy', path='track_voy', required=True, example=None, ui_kind='text'),
        IOFieldBinding(name='finance_date', path='finance_date', required=True, example='1782316800', ui_kind='text'),
        IOFieldBinding(name='pol_cn', path='pol_cn', required=True, example='青岛流亭机场', ui_kind='text'),
        IOFieldBinding(name='pol_country_id', path='pol_country_id', required=True, example='1', ui_kind='text'),
        IOFieldBinding(name='pol_country', path='pol_country', required=True, example='CHINA', ui_kind='text'),
        IOFieldBinding(name='pol_country_cn', path='pol_country_cn', required=True, example='中国', ui_kind='text'),
        IOFieldBinding(name='pod_cn', path='pod_cn', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='pot_cn', path='pot_cn', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='del_cn', path='del_cn', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='country_id', path='country_id', required=True, example='1', ui_kind='text'),
        IOFieldBinding(name='country_name_cn', path='country_name_cn', required=True, example='中国', ui_kind='text'),
        IOFieldBinding(name='customer_period', path='customer_period', required=True, example='120', ui_kind='text'),
        IOFieldBinding(name='customer_settlement_date', path='customer_settlement_date', required=True, example='10', ui_kind='text'),
        IOFieldBinding(name='period_rule', path='period_rule', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='term_rule_name', path='term_rule_name', required=True, example=None, ui_kind='text'),
        IOFieldBinding(name='customer_due_date', path='customer_due_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='customer_put_date', path='customer_put_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='customer_payment_collection_date', path='customer_payment_collection_date', required=True, example=None, ui_kind='text'),
        IOFieldBinding(name='customer_put_date_manual', path='customer_put_date_manual', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='customer_put_writeoff_date', path='customer_put_writeoff_date', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='supplier_due_date', path='supplier_due_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='discount_start', path='discount_start', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='discount_rule', path='discount_rule', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='discount_end', path='discount_end', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='discount_ratio', path='discount_ratio', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='discount_status', path='discount_status', required=True, example='2', ui_kind='text'),
        IOFieldBinding(name='discount_currency', path='discount_currency', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='book_upload_date', path='book_upload_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='trans_cost_put_preserve_date', path='trans_cost_put_preserve_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='bl_no_upload_date', path='bl_no_upload_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='supplier_invoice_date', path='supplier_invoice_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='supplier_invoice_taketime', path='supplier_invoice_taketime', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='real_cost_date', path='real_cost_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='customer_invoice_request_date', path='customer_invoice_request_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='first_financing_doc_ok_date', path='first_financing_doc_ok_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='second_financing_doc_ok_date', path='second_financing_doc_ok_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='insurance_doc_ok_date', path='insurance_doc_ok_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='customer_confirm_date', path='customer_confirm_date', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='is_delayed_recovery', path='is_delayed_recovery', required=True, example='否', ui_kind='text'),
        IOFieldBinding(name='delayed_recovery_usd', path='delayed_recovery_usd', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='delayed_recovery_cny', path='delayed_recovery_cny', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='delayed_time', path='delayed_time', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='expect_fee_status', path='expect_fee_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='real_fee_status', path='real_fee_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='fee_lock_status', path='fee_lock_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='pay_account_status', path='pay_account_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='account_status', path='account_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='real_pay_usd', path='real_pay_usd', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='real_pay_cny', path='real_pay_cny', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='real_put_usd', path='real_put_usd', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='real_put_cny', path='real_put_cny', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='real_put_discount_rate', path='real_put_discount_rate', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='exchange_rate', path='exchange_rate', required=True, example='6.8067', ui_kind='text'),
        IOFieldBinding(name='folde_pay_usd', path='folde_pay_usd', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='folde_put_usd', path='folde_put_usd', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='folde_pay_total', path='folde_pay_total', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='folde_put_total', path='folde_put_total', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='gross_margin', path='gross_margin', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='gross_margin_rate', path='gross_margin_rate', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='is_special_pay', path='is_special_pay', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='is_loan_before_invoice', path='is_loan_before_invoice', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='is_fee_miss', path='is_fee_miss', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='fee_miss_name', path='fee_miss_name', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='cancel_remark', path='cancel_remark', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='cancel_time', path='cancel_time', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='effective_id', path='effective_id', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='effective_by', path='effective_by', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='effective_time', path='effective_time', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='create_id', path='create_id', required=True, example='828', ui_kind='text'),
        IOFieldBinding(name='create_by', path='create_by', required=True, example='GIMBAL', ui_kind='text'),
        IOFieldBinding(name='create_time', path='create_time', required=True, example='1782882887', ui_kind='text'),
        IOFieldBinding(name='update_id', path='update_id', required=True, example='828', ui_kind='text'),
        IOFieldBinding(name='update_by', path='update_by', required=True, example='GIMBAL', ui_kind='text'),
        IOFieldBinding(name='update_time', path='update_time', required=True, example='1782882935', ui_kind='text'),
        IOFieldBinding(name='delete_time', path='delete_time', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='business_time', path='business_time', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='main_ids', path='main_ids', required=True, example=',15,16,1,', ui_kind='text'),
        IOFieldBinding(name='reverse_status', path='reverse_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='proprietary_business_status', path='proprietary_business_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='loan_status', path='loan_status', required=True, example=None, ui_kind='text'),
        IOFieldBinding(name='first_status', path='first_status', required=True, example=None, ui_kind='text'),
        IOFieldBinding(name='second_status', path='second_status', required=True, example=None, ui_kind='text'),
        IOFieldBinding(name='loan_pay_status', path='loan_pay_status', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='change_type', path='change_type', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='copy_order_id', path='copy_order_id', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='real_fee_locked', path='real_fee_locked', required=True, example=False, ui_kind='boolean'),
        IOFieldBinding(name='is_usd_project', path='is_usd_project', required=True, example='2', ui_kind='text'),
        IOFieldBinding(name='pay_status', path='pay_status', required=True, example='1', ui_kind='text'),
        IOFieldBinding(name='is_sync_es', path='is_sync_es', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='expect_discount_status', path='expect_discount_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='real_discount_status', path='real_discount_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='entrust_status', path='entrust_status', required=True, example='2', ui_kind='text'),
        IOFieldBinding(name='remark', path='remark', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='audit_type', path='audit_type', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='is_system_generate', path='is_system_generate', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='is_financing', path='is_financing', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='confirm_status', path='confirm_status', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='is_traverse', path='is_traverse', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='financing_apply_amount', path='financing_apply_amount', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='financing_apply_amount_cny', path='financing_apply_amount_cny', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='financing_apply_amount_usd', path='financing_apply_amount_usd', required=True, example='0.00', ui_kind='text'),
        IOFieldBinding(name='sys_upttime', path='sys_upttime', required=True, example='2026-07-01 13:15:35', ui_kind='text'),
        IOFieldBinding(name='customer_put_date_desc', path='customer_put_date_desc', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='deposit_refund_month', path='deposit_refund_month', required=True, example=None, ui_kind='text'),
        IOFieldBinding(name='payment_type', path='payment_type', required=True, example='0', ui_kind='text'),
        IOFieldBinding(name='reverse_status_name', path='reverse_status_name', required=True, example='否', ui_kind='text'),
        IOFieldBinding(name='is_delayed_recovery_name', path='is_delayed_recovery_name', required=True, example='否', ui_kind='text'),
        IOFieldBinding(name='order_finance_arr', path='order_finance_arr', required=True, example=[], ui_kind='json'),
        IOFieldBinding(name='order_main_bank_arr', path='order_main_bank_arr', required=True, example=[], ui_kind='json'),
        IOFieldBinding(name='order_sub', path='order_sub', required=True, example=[], ui_kind='json'),
        IOFieldBinding(name='order_sub_no', path='order_sub_no', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='service_project', path='service_project', required=True, example={'booking_space': False, 'customs_clearance': False, 'manifest': False, 'insurance': False, 'trucking': False}, ui_kind='json'),
        IOFieldBinding(name='service_project_amount', path='service_project_amount', required=True, example={'booking_space': False, 'customs_clearance': False, 'manifest': False, 'insurance': False, 'trucking': False}, ui_kind='json'),
        IOFieldBinding(name='finance_status', path='finance_status', required=True, example=True, ui_kind='boolean'),
        IOFieldBinding(name='main_ids_name', path='main_ids_name', required=True, example='易汇瀚,易海,易航道', ui_kind='text'),
        IOFieldBinding(name='policy_main_arr', path='policy_main_arr', required=True, example=[{'fee_main_id': '15', 'main_name': '成都易汇瀚供应链管理有限公司'}, {'fee_main_id': '16', 'main_name': '青岛易海供应链管理有限公司'}, {'fee_main_id': '1', 'main_name': '青岛易航道物流科技有限公司'}], ui_kind='json'),
        IOFieldBinding(name='policy_type_name', path='policy_type_name', required=True, example='结算业务', ui_kind='text'),
        IOFieldBinding(name='business_type_name', path='business_type_name', required=True, example='海运整箱', ui_kind='text'),
        IOFieldBinding(name='cargo_type_name', path='cargo_type_name', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='period_rule_name', path='period_rule_name', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='trade_term_name', path='trade_term_name', required=True, example='CIF', ui_kind='text'),
        IOFieldBinding(name='carrier_name', path='carrier_name', required=True, example='中国远洋运输（集团）总公司', ui_kind='text'),
        IOFieldBinding(name='terms_transport_name', path='terms_transport_name', required=True, example='CY/CY', ui_kind='text'),
        IOFieldBinding(name='terms_payment_name', path='terms_payment_name', required=True, example='T/T', ui_kind='text'),
        IOFieldBinding(name='pay_type_name', path='pay_type_name', required=True, example='FREIGHT PREPAID', ui_kind='text'),
        IOFieldBinding(name='m_delivery_type_name', path='m_delivery_type_name', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='payment_type_name', path='payment_type_name', required=True, example='空', ui_kind='text'),
        IOFieldBinding(name='audit', path='audit', required=True, example=[], ui_kind='json'),
        IOFieldBinding(name='enable', path='enable', required=True, example='1', ui_kind='text'),
        IOFieldBinding(name='policy_match', path='policy_match', required=True, example='semi', ui_kind='text'),
        IOFieldBinding(name='policy_match_name', path='policy_match_name', required=True, example='手动选择', ui_kind='text'),
        IOFieldBinding(name='real_discount_status_name', path='real_discount_status_name', required=True, example='—', ui_kind='text'),
        IOFieldBinding(name='expect_discount_status_name', path='expect_discount_status_name', required=True, example='—', ui_kind='text'),
        IOFieldBinding(name='expect_policy_status_name', path='expect_policy_status_name', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='policy_status_name', path='policy_status_name', required=True, example='', ui_kind='text'),
        IOFieldBinding(name='subsidy_category_name', path='subsidy_category_name', required=True, example='—', ui_kind='text'),
        IOFieldBinding(name='expect_subsidy_category_name', path='expect_subsidy_category_name', required=True, example='—', ui_kind='text'),
        IOFieldBinding(name='real_subsidy_category_name', path='real_subsidy_category_name', required=True, example='—', ui_kind='text'),
        IOFieldBinding(name='action', path='action', required=True, example='check', ui_kind='text'),
        IOFieldBinding(name='order_file', path='order_file', required=True, example=[], ui_kind='json'),
        ],
        schema_={},
    ),
    responses={
        200: ResponseSpec(
            status=200,
            description="成功",
        ),
    },
    version="1.0.0",
)
