"""fin.order.order_book —— 提交订舱文件接口契约。在 scen_test_14 中出现1次。"""

from typing import Final

from gimbal_plate.systems.fin.system_info import (
    FIN_DEFAULT_AUTHOR,
    FIN_DEFAULT_MODULE,
    FIN_DEFAULT_OWNER,
    FIN_DEFAULT_PRIORITY,
    FIN_DEFAULT_TAGS,
    FIN_DEFAULT_VERSION,
    FIN_SYSTEM,
)
from gimbal_plate.schema.endpoint import (
    ApiSpec,
    EndpointSpec,
    DeclarationEntry,
    RequestSpec,
    ResponseSpec,
    EndpointMetadata,
)


ORDER_ORDER_BOOK: Final[EndpointSpec] = EndpointSpec(
    id="fin.order.order_book",
    system=FIN_SYSTEM,
    service="fin-service",
    name="提交订舱文件",
    description="由 Scenario_Test_14 提取: 提交订舱文件",
    api=ApiSpec(service="fin-service", method="POST", path="/api/order/order/orderBook", auth="bearer", timeout_seconds=30.0),
    request=RequestSpec(
        body_type='json',
        
        declarations=[
            DeclarationEntry(name='bl_no', path='$.bl_no', type='string', example='Codfish-IPKZ-Test', ui_kind='text'),
            DeclarationEntry(name='order_id', path='$.order_id', type='string', example='354066893969032192', ui_kind='text'),
            DeclarationEntry(name='order_no', path='$.order_no', type='string', example='YWDD20260904110854', ui_kind='text'),
            DeclarationEntry(name='track_bl_no', path='$.track_bl_no', type='string', example='Codfish-IPKZ-Test', ui_kind='text'),
            DeclarationEntry(name='entrust_status', path='$.entrust_status', type='string', example='2', description='1: 委托订单 2: 订单已分发', ui_kind='text'),
            DeclarationEntry(name='action', path='$.action', type='string', example='check', description='check 检查 | submit 提交', ui_kind='text'),
            # 2026-09-06 结构化(对齐 order_add 同款):customer_file_list 行形状
            # example 单例承载 → 容器模板 children;9 业务键,_XID 前端行标记
            # 不进目录;弃 example,深层无值不落 None 骨架(supplier/container 同款纪律)
            DeclarationEntry(name='customer_file_list', path='$.customer_file_list', type='array',
                children=[
                    DeclarationEntry(name='client_company_id', path='$.customer_file_list.client_company_id', type='string', ui_kind='text'),
                    DeclarationEntry(name='client_company_name', path='$.customer_file_list.client_company_name', type='string', ui_kind='text'),
                    DeclarationEntry(name='trustee_company_id', path='$.customer_file_list.trustee_company_id', type='string', ui_kind='text'),
                    DeclarationEntry(name='trustee_company_name', path='$.customer_file_list.trustee_company_name', type='string', ui_kind='text'),
                    DeclarationEntry(name='document_type', path='$.customer_file_list.document_type', type='string', ui_kind='text'),
                    DeclarationEntry(name='file_url', path='$.customer_file_list.file_url', type='string', ui_kind='text'),
                    DeclarationEntry(name='file_name', path='$.customer_file_list.file_name', type='string', ui_kind='text'),
                    DeclarationEntry(name='file_id', path='$.customer_file_list.file_id', type='string', ui_kind='text'),
                    DeclarationEntry(name='file_type', path='$.customer_file_list.file_type', type='string', ui_kind='text'),
                ]),
            # 传递面(carry 通道,不进表单,值随 platform 两层值表走)
            DeclarationEntry(name='client_expand_name', path='$.client_expand_name', state='carry', type='string'),
            DeclarationEntry(name='m_delivery_type', path='$.m_delivery_type', state='carry', type='string'),
            DeclarationEntry(name='customer_id', path='$.customer_id', state='carry', type='string'),
            DeclarationEntry(name='customer_name', path='$.customer_name', state='carry', type='string'),
            DeclarationEntry(name='service_id', path='$.service_id', state='carry', type='string'),
            DeclarationEntry(name='service_name', path='$.service_name', state='carry', type='string'),
            DeclarationEntry(name='sale_id', path='$.sale_id', state='carry', type='string'),
            DeclarationEntry(name='sale_name', path='$.sale_name', state='carry', type='string'),
            DeclarationEntry(name='operator_id', path='$.operator_id', state='carry', type='string'),
            DeclarationEntry(name='operator_name', path='$.operator_name', state='carry', type='string'),
            DeclarationEntry(name='customer_contact_id', path='$.customer_contact_id', state='carry', type='string'),
            DeclarationEntry(name='customer_contact_name', path='$.customer_contact_name', state='carry', type='string'),
            DeclarationEntry(name='main_sort', path='$.main_sort', state='carry', type='string'),
            DeclarationEntry(name='policy_id', path='$.policy_id', state='carry', type='string'),
            DeclarationEntry(name='policy_name', path='$.policy_name', state='carry', type='string'),
            DeclarationEntry(name='policy_type', path='$.policy_type', state='carry', type='string'),
            DeclarationEntry(name='settle_type', path='$.settle_type', state='carry', type='string'),
            DeclarationEntry(name='settle_type_name', path='$.settle_type_name', state='carry', type='string'),
            DeclarationEntry(name='customer_product_id', path='$.customer_product_id', state='carry', type='string'),
            DeclarationEntry(name='product_name', path='$.product_name', state='carry', type='string'),
            DeclarationEntry(name='deposit_type', path='$.deposit_type', state='carry', type='string'),
            DeclarationEntry(name='deposit_type_name', path='$.deposit_type_name', state='carry', type='string'),
            DeclarationEntry(name='period_delay_type', path='$.period_delay_type', state='carry', type='string'),
            DeclarationEntry(name='period_delay_type_name', path='$.period_delay_type_name', state='carry', type='string'),
            DeclarationEntry(name='service_items', path='$.service_items', state='carry', type='array'),
            DeclarationEntry(name='business_type', path='$.business_type', state='carry', type='string'),
            DeclarationEntry(name='trade_term', path='$.trade_term', state='carry', type='string'),
            DeclarationEntry(name='carrier', path='$.carrier', state='carry', type='string'),
            DeclarationEntry(name='carrier_id', path='$.carrier_id', state='carry', type='string'),
            DeclarationEntry(name='etd', path='$.etd', state='carry', type='integer'),
            DeclarationEntry(name='atd', path='$.atd', state='carry', type='integer'),
            DeclarationEntry(name='ship_name', path='$.ship_name', state='carry', type='string'),
            DeclarationEntry(name='voy', path='$.voy', state='carry', type='string'),
            DeclarationEntry(name='pol', path='$.pol', state='carry', type='string'),
            DeclarationEntry(name='pot', path='$.pot', state='carry', type='string'),
            DeclarationEntry(name='pod', path='$.pod', state='carry', type='string'),
            DeclarationEntry(name='del', path='$.del', state='carry', type='string'),
            DeclarationEntry(name='country_name', path='$.country_name', state='carry', type='string'),
            DeclarationEntry(name='airline_type', path='$.airline_type', state='carry', type='string'),
            DeclarationEntry(name='ocean_type', path='$.ocean_type', state='carry', type='string'),
            DeclarationEntry(name='terms_payment', path='$.terms_payment', state='carry', type='string'),
            DeclarationEntry(name='terms_transport', path='$.terms_transport', state='carry', type='string'),
            DeclarationEntry(name='pay_type', path='$.pay_type', state='carry', type='string'),
            DeclarationEntry(name='customer_order_sn', path='$.customer_order_sn', state='carry', type='string'),
            DeclarationEntry(name='terms_shipment', path='$.terms_shipment', state='carry', type='string'),
            DeclarationEntry(name='shipper', path='$.shipper', state='carry', type='string'),
            DeclarationEntry(name='consignee', path='$.consignee', state='carry', type='string'),
            DeclarationEntry(name='notifier', path='$.notifier', state='carry', type='string'),
            DeclarationEntry(name='ship_mark', path='$.ship_mark', state='carry', type='string'),
            DeclarationEntry(name='commodity', path='$.commodity', state='carry', type='string'),
            DeclarationEntry(name='notes', path='$.notes', state='carry', type='string'),
            DeclarationEntry(name='cargo_type', path='$.cargo_type', state='carry', type='string'),
            DeclarationEntry(name='packer', path='$.packer', state='carry', type='string'),
            DeclarationEntry(name='num', path='$.num', state='carry', type='string'),
            DeclarationEntry(name='gross_weight', path='$.gross_weight', state='carry', type='string'),
            DeclarationEntry(name='bulk', path='$.bulk', state='carry', type='string'),
            DeclarationEntry(name='sea_trans_cost', path='$.sea_trans_cost', state='carry', type='string'),
            DeclarationEntry(name='teu', path='$.teu', state='carry', type='string'),
            DeclarationEntry(name='volume', path='$.volume', state='carry', type='string'),
            DeclarationEntry(name='volume_desc', path='$.volume_desc', state='carry', type='string'),
            DeclarationEntry(name='order_sn', path='$.order_sn', state='carry', type='string'),
            DeclarationEntry(name='status', path='$.status', state='carry', type='integer'),
            DeclarationEntry(name='sea_trans_currency', path='$.sea_trans_currency', state='carry', type='string'),
            DeclarationEntry(name='message_board', path='$.message_board', state='carry', type='array'),
            # 2026-09-05 对齐 order_order_add:supplier/container 弃 carry 整传,
            # 容器与子孙一律 form(22/6 键行模板,与 order_add 同构);
            # 深实例叶子并入容器模板 children,不带 default/example(body 零漂移)
            DeclarationEntry(name='supplier', path='$.supplier', state='form', type='array',
                children=[
                    DeclarationEntry(name='order_supplier_id', path='$.supplier.order_supplier_id', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='order_id', path='$.supplier.order_id', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='isset_supplier', path='$.supplier.isset_supplier', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='is_primary', path='$.supplier.is_primary', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='supplier_id', path='$.supplier.supplier_id', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='supplier_name', path='$.supplier.supplier_name', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='settle_object_id', path='$.supplier.settle_object_id', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='user_id', path='$.supplier.user_id', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='user_name', path='$.supplier.user_name', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='service_item', path='$.supplier.service_item', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='supplier_period', path='$.supplier.supplier_period', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='settlement_date', path='$.supplier.settlement_date', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='supplier_pay_date', path='$.supplier.supplier_pay_date', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='is_manual', path='$.supplier.is_manual', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='sys_upttime', path='$.supplier.sys_upttime', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='pay_time_limit', path='$.supplier.pay_time_limit', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='supplier_pay_date_desc', path='$.supplier.supplier_pay_date_desc', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='settle_type', path='$.supplier.settle_type', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='supplier_label', path='$.supplier.supplier_label', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='settle_type_name', path='$.supplier.settle_type_name', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='service_item_name', path='$.supplier.service_item_name', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='isset_fee', path='$.supplier.isset_fee', state='form', type='boolean', ui_kind='boolean'),
                ]),
            DeclarationEntry(name='container', path='$.container', state='form', type='array',
                children=[
                    DeclarationEntry(name='order_container_id', path='$.container.order_container_id', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='box_type', path='$.container.box_type', state='form', type='string', ui_kind='text'),
                    DeclarationEntry(name='box_num', path='$.container.box_num', state='form', type='string', ui_kind='text'),
                    # P2(2026-09-05):噪声子数组盖 collapse(区块级折叠,默认收起)
                    DeclarationEntry(name='box_no', path='$.container.box_no', state='collapse', type='array'),
                    DeclarationEntry(name='seal_number', path='$.container.seal_number', state='collapse', type='array'),
                    DeclarationEntry(name='sea_trans_unit_price', path='$.container.sea_trans_unit_price', state='form', type='number', ui_kind='number'),
                ]),
            DeclarationEntry(name='customer_category', path='$.customer_category', state='carry', type='string'),
            DeclarationEntry(name='customer_tax_number', path='$.customer_tax_number', state='carry', type='string'),
            DeclarationEntry(name='customer_address_cn', path='$.customer_address_cn', state='carry', type='string'),
            DeclarationEntry(name='client_expand_id', path='$.client_expand_id', state='carry', type='string'),
            DeclarationEntry(name='customer_contact_phone', path='$.customer_contact_phone', state='carry', type='string'),
            DeclarationEntry(name='customer_main_id', path='$.customer_main_id', state='carry', type='string'),
            DeclarationEntry(name='customer_main_name', path='$.customer_main_name', state='carry', type='string'),
            DeclarationEntry(name='business_main_id', path='$.business_main_id', state='carry', type='string'),
            DeclarationEntry(name='business_main_name', path='$.business_main_name', state='carry', type='string'),
            DeclarationEntry(name='fund_code', path='$.fund_code', state='carry', type='string'),
            DeclarationEntry(name='fund_name', path='$.fund_name', state='carry', type='string'),
            DeclarationEntry(name='track_atd', path='$.track_atd', state='carry', type='string'),
            DeclarationEntry(name='track_eta', path='$.track_eta', state='carry', type='string'),
            DeclarationEntry(name='track_ata', path='$.track_ata', state='carry', type='string'),
            DeclarationEntry(name='track_stcs', path='$.track_stcs', state='carry', type='string'),
            DeclarationEntry(name='track_ship_name', path='$.track_ship_name', state='carry', type='string'),
            DeclarationEntry(name='track_voy', path='$.track_voy', state='carry', type='string'),
            DeclarationEntry(name='finance_date', path='$.finance_date', state='carry', type='string'),
            DeclarationEntry(name='pol_cn', path='$.pol_cn', state='carry', type='string'),
            DeclarationEntry(name='pol_country_id', path='$.pol_country_id', state='carry', type='string'),
            DeclarationEntry(name='pol_country', path='$.pol_country', state='carry', type='string'),
            DeclarationEntry(name='pol_country_cn', path='$.pol_country_cn', state='carry', type='string'),
            DeclarationEntry(name='pod_cn', path='$.pod_cn', state='carry', type='string'),
            DeclarationEntry(name='pot_cn', path='$.pot_cn', state='carry', type='string'),
            DeclarationEntry(name='del_cn', path='$.del_cn', state='carry', type='string'),
            DeclarationEntry(name='country_id', path='$.country_id', state='carry', type='string'),
            DeclarationEntry(name='country_name_cn', path='$.country_name_cn', state='carry', type='string'),
            DeclarationEntry(name='customer_period', path='$.customer_period', state='carry', type='string'),
            DeclarationEntry(name='customer_settlement_date', path='$.customer_settlement_date', state='carry', type='string'),
            DeclarationEntry(name='period_rule', path='$.period_rule', state='carry', type='string'),
            DeclarationEntry(name='term_rule_name', path='$.term_rule_name', state='carry', type='string'),
            DeclarationEntry(name='customer_due_date', path='$.customer_due_date', state='carry', type='string'),
            DeclarationEntry(name='customer_put_date', path='$.customer_put_date', state='carry', type='string'),
            DeclarationEntry(name='customer_payment_collection_date', path='$.customer_payment_collection_date', state='carry', type='string'),
            DeclarationEntry(name='customer_put_date_manual', path='$.customer_put_date_manual', state='carry', type='string'),
            DeclarationEntry(name='customer_put_writeoff_date', path='$.customer_put_writeoff_date', state='carry', type='string'),
            DeclarationEntry(name='supplier_due_date', path='$.supplier_due_date', state='carry', type='string'),
            DeclarationEntry(name='discount_start', path='$.discount_start', state='carry', type='string'),
            DeclarationEntry(name='discount_rule', path='$.discount_rule', state='carry', type='string'),
            DeclarationEntry(name='discount_end', path='$.discount_end', state='carry', type='string'),
            DeclarationEntry(name='discount_ratio', path='$.discount_ratio', state='carry', type='string'),
            DeclarationEntry(name='discount_status', path='$.discount_status', state='carry', type='string'),
            DeclarationEntry(name='discount_currency', path='$.discount_currency', state='carry', type='string'),
            DeclarationEntry(name='book_upload_date', path='$.book_upload_date', state='carry', type='string'),
            DeclarationEntry(name='trans_cost_put_preserve_date', path='$.trans_cost_put_preserve_date', state='carry', type='string'),
            DeclarationEntry(name='bl_no_upload_date', path='$.bl_no_upload_date', state='carry', type='string'),
            DeclarationEntry(name='supplier_invoice_date', path='$.supplier_invoice_date', state='carry', type='string'),
            DeclarationEntry(name='supplier_invoice_taketime', path='$.supplier_invoice_taketime', state='carry', type='string'),
            DeclarationEntry(name='real_cost_date', path='$.real_cost_date', state='carry', type='string'),
            DeclarationEntry(name='customer_invoice_request_date', path='$.customer_invoice_request_date', state='carry', type='string'),
            DeclarationEntry(name='first_financing_doc_ok_date', path='$.first_financing_doc_ok_date', state='carry', type='string'),
            DeclarationEntry(name='second_financing_doc_ok_date', path='$.second_financing_doc_ok_date', state='carry', type='string'),
            DeclarationEntry(name='insurance_doc_ok_date', path='$.insurance_doc_ok_date', state='carry', type='string'),
            DeclarationEntry(name='customer_confirm_date', path='$.customer_confirm_date', state='carry', type='string'),
            DeclarationEntry(name='is_delayed_recovery', path='$.is_delayed_recovery', state='carry', type='string'),
            DeclarationEntry(name='delayed_recovery_usd', path='$.delayed_recovery_usd', state='carry', type='string'),
            DeclarationEntry(name='delayed_recovery_cny', path='$.delayed_recovery_cny', state='carry', type='string'),
            DeclarationEntry(name='delayed_time', path='$.delayed_time', state='carry', type='string'),
            DeclarationEntry(name='expect_fee_status', path='$.expect_fee_status', state='carry', type='string'),
            DeclarationEntry(name='real_fee_status', path='$.real_fee_status', state='carry', type='string'),
            DeclarationEntry(name='fee_lock_status', path='$.fee_lock_status', state='carry', type='string'),
            DeclarationEntry(name='pay_account_status', path='$.pay_account_status', state='carry', type='string'),
            DeclarationEntry(name='account_status', path='$.account_status', state='carry', type='string'),
            DeclarationEntry(name='real_pay_usd', path='$.real_pay_usd', state='carry', type='string'),
            DeclarationEntry(name='real_pay_cny', path='$.real_pay_cny', state='carry', type='string'),
            DeclarationEntry(name='real_put_usd', path='$.real_put_usd', state='carry', type='string'),
            DeclarationEntry(name='real_put_cny', path='$.real_put_cny', state='carry', type='string'),
            DeclarationEntry(name='real_put_discount_rate', path='$.real_put_discount_rate', state='carry', type='string'),
            DeclarationEntry(name='exchange_rate', path='$.exchange_rate', state='carry', type='string'),
            DeclarationEntry(name='folde_pay_usd', path='$.folde_pay_usd', state='carry', type='string'),
            DeclarationEntry(name='folde_put_usd', path='$.folde_put_usd', state='carry', type='string'),
            DeclarationEntry(name='folde_pay_total', path='$.folde_pay_total', state='carry', type='string'),
            DeclarationEntry(name='folde_put_total', path='$.folde_put_total', state='carry', type='string'),
            DeclarationEntry(name='gross_margin', path='$.gross_margin', state='carry', type='string'),
            DeclarationEntry(name='gross_margin_rate', path='$.gross_margin_rate', state='carry', type='string'),
            DeclarationEntry(name='is_special_pay', path='$.is_special_pay', state='carry', type='string'),
            DeclarationEntry(name='is_loan_before_invoice', path='$.is_loan_before_invoice', state='carry', type='string'),
            DeclarationEntry(name='is_fee_miss', path='$.is_fee_miss', state='carry', type='string'),
            DeclarationEntry(name='fee_miss_name', path='$.fee_miss_name', state='carry', type='string'),
            DeclarationEntry(name='cancel_remark', path='$.cancel_remark', state='carry', type='string'),
            DeclarationEntry(name='cancel_time', path='$.cancel_time', state='carry', type='string'),
            DeclarationEntry(name='effective_id', path='$.effective_id', state='carry', type='string'),
            DeclarationEntry(name='effective_by', path='$.effective_by', state='carry', type='string'),
            DeclarationEntry(name='effective_time', path='$.effective_time', state='carry', type='string'),
            DeclarationEntry(name='create_id', path='$.create_id', state='carry', type='string'),
            DeclarationEntry(name='create_by', path='$.create_by', state='carry', type='string'),
            # create_time/update_time 提升 form(2026-09-06):Test_15 起以
            # time_offset 变量驱动,表单须可见可编辑;同类审计字段仍 carry
            DeclarationEntry(name='create_time', path='$.create_time', state='form', type='string'),
            DeclarationEntry(name='update_id', path='$.update_id', state='carry', type='string'),
            DeclarationEntry(name='update_by', path='$.update_by', state='carry', type='string'),
            DeclarationEntry(name='update_time', path='$.update_time', state='form', type='string'),
            DeclarationEntry(name='delete_time', path='$.delete_time', state='carry', type='string'),
            DeclarationEntry(name='business_time', path='$.business_time', state='carry', type='string'),
            DeclarationEntry(name='main_ids', path='$.main_ids', state='carry', type='string'),
            DeclarationEntry(name='reverse_status', path='$.reverse_status', state='carry', type='string'),
            DeclarationEntry(name='proprietary_business_status', path='$.proprietary_business_status', state='carry', type='string'),
            DeclarationEntry(name='loan_status', path='$.loan_status', state='carry', type='string'),
            DeclarationEntry(name='first_status', path='$.first_status', state='carry', type='string'),
            DeclarationEntry(name='second_status', path='$.second_status', state='carry', type='string'),
            DeclarationEntry(name='loan_pay_status', path='$.loan_pay_status', state='carry', type='string'),
            DeclarationEntry(name='change_type', path='$.change_type', state='carry', type='string'),
            DeclarationEntry(name='copy_order_id', path='$.copy_order_id', state='carry', type='string'),
            DeclarationEntry(name='real_fee_locked', path='$.real_fee_locked', state='carry', type='boolean'),
            DeclarationEntry(name='is_usd_project', path='$.is_usd_project', state='carry', type='string'),
            DeclarationEntry(name='pay_status', path='$.pay_status', state='carry', type='string'),
            DeclarationEntry(name='is_sync_es', path='$.is_sync_es', state='carry', type='string'),
            DeclarationEntry(name='expect_discount_status', path='$.expect_discount_status', state='carry', type='string'),
            DeclarationEntry(name='real_discount_status', path='$.real_discount_status', state='carry', type='string'),
            DeclarationEntry(name='remark', path='$.remark', state='carry', type='string'),
            DeclarationEntry(name='audit_type', path='$.audit_type', state='carry', type='string'),
            DeclarationEntry(name='is_system_generate', path='$.is_system_generate', state='carry', type='string'),
            DeclarationEntry(name='is_financing', path='$.is_financing', state='carry', type='string'),
            DeclarationEntry(name='confirm_status', path='$.confirm_status', state='carry', type='string'),
            DeclarationEntry(name='is_traverse', path='$.is_traverse', state='carry', type='string'),
            DeclarationEntry(name='financing_apply_amount', path='$.financing_apply_amount', state='carry', type='string'),
            DeclarationEntry(name='financing_apply_amount_cny', path='$.financing_apply_amount_cny', state='carry', type='string'),
            DeclarationEntry(name='financing_apply_amount_usd', path='$.financing_apply_amount_usd', state='carry', type='string'),
            DeclarationEntry(name='sys_upttime', path='$.sys_upttime', state='form', type='string', ui_kind='text'),
            DeclarationEntry(name='receive_time_limit', path='$.receive_time_limit', state='carry', type='string'),
            DeclarationEntry(name='customer_put_date_desc', path='$.customer_put_date_desc', state='carry', type='string'),
            DeclarationEntry(name='deposit_refund_day', path='$.deposit_refund_day', state='carry', type='string'),
            DeclarationEntry(name='deposit_settlement_date', path='$.deposit_settlement_date', state='carry', type='string'),
            DeclarationEntry(name='deposit_refund_month', path='$.deposit_refund_month', state='carry', type='string'),
            DeclarationEntry(name='payment_type', path='$.payment_type', state='carry', type='string'),
            DeclarationEntry(name='product_id', path='$.product_id', state='carry', type='string'),
            DeclarationEntry(name='revoke_status', path='$.revoke_status', state='carry', type='string'),
            DeclarationEntry(name='revoke_type', path='$.revoke_type', state='carry', type='string'),
            DeclarationEntry(name='asset_status', path='$.asset_status', state='carry', type='string'),
            DeclarationEntry(name='revoke_failure_reason', path='$.revoke_failure_reason', state='carry', type='string'),
            DeclarationEntry(name='repayment_date', path='$.repayment_date', state='carry', type='string'),
            DeclarationEntry(name='repay_warn_time', path='$.repay_warn_time', state='carry', type='string'),
            DeclarationEntry(name='reverse_status_name', path='$.reverse_status_name', state='carry', type='string'),
            DeclarationEntry(name='is_delayed_recovery_name', path='$.is_delayed_recovery_name', state='carry', type='string'),
            DeclarationEntry(name='order_finance_arr', path='$.order_finance_arr', state='carry', type='array'),
            DeclarationEntry(name='order_main_bank_arr', path='$.order_main_bank_arr', state='carry', type='array'),
            DeclarationEntry(name='order_sub', path='$.order_sub', state='carry', type='array'),
            DeclarationEntry(name='order_sub_no', path='$.order_sub_no', state='carry', type='string'),
            # 2026-09-06 补录行形状(对齐 order_add 同款):service_project/
            # _amount 实抓为固定 5 键布尔(service_items 词表);carry 容器
            # ⇒ 子孙一律 carry(整传一致性)
            DeclarationEntry(name='service_project', path='$.service_project', state='carry', type='object',
                children=[
                    DeclarationEntry(name='booking_space', path='$.service_project.booking_space', state='carry', type='boolean'),
                    DeclarationEntry(name='customs_clearance', path='$.service_project.customs_clearance', state='carry', type='boolean'),
                    DeclarationEntry(name='manifest', path='$.service_project.manifest', state='carry', type='boolean'),
                    DeclarationEntry(name='insurance', path='$.service_project.insurance', state='carry', type='boolean'),
                    DeclarationEntry(name='trucking', path='$.service_project.trucking', state='carry', type='boolean'),
                ]),
            DeclarationEntry(name='service_project_amount', path='$.service_project_amount', state='carry', type='object',
                children=[
                    DeclarationEntry(name='booking_space', path='$.service_project_amount.booking_space', state='carry', type='boolean'),
                    DeclarationEntry(name='customs_clearance', path='$.service_project_amount.customs_clearance', state='carry', type='boolean'),
                    DeclarationEntry(name='manifest', path='$.service_project_amount.manifest', state='carry', type='boolean'),
                    DeclarationEntry(name='insurance', path='$.service_project_amount.insurance', state='carry', type='boolean'),
                    DeclarationEntry(name='trucking', path='$.service_project_amount.trucking', state='carry', type='boolean'),
                ]),
            DeclarationEntry(name='finance_status', path='$.finance_status', state='carry', type='boolean'),
            DeclarationEntry(name='main_ids_name', path='$.main_ids_name', state='carry', type='string'),
            # 2026-09-06 补录行形状(对齐 order_add 同款):policy_main_arr
            # 双 body 实抓 2 键行(fee_main_id/main_name);carry 容器 ⇒ 子孙 carry
            DeclarationEntry(name='policy_main_arr', path='$.policy_main_arr', state='carry', type='array',
                children=[
                    DeclarationEntry(name='fee_main_id', path='$.policy_main_arr.fee_main_id', state='carry', type='string'),
                    DeclarationEntry(name='main_name', path='$.policy_main_arr.main_name', state='carry', type='string'),
                ]),
            DeclarationEntry(name='policy_type_name', path='$.policy_type_name', state='carry', type='string'),
            DeclarationEntry(name='business_type_name', path='$.business_type_name', state='carry', type='string'),
            DeclarationEntry(name='cargo_type_name', path='$.cargo_type_name', state='carry', type='string'),
            DeclarationEntry(name='period_rule_name', path='$.period_rule_name', state='carry', type='string'),
            DeclarationEntry(name='trade_term_name', path='$.trade_term_name', state='carry', type='string'),
            DeclarationEntry(name='carrier_name', path='$.carrier_name', state='carry', type='string'),
            DeclarationEntry(name='terms_transport_name', path='$.terms_transport_name', state='carry', type='string'),
            DeclarationEntry(name='terms_payment_name', path='$.terms_payment_name', state='carry', type='string'),
            DeclarationEntry(name='pay_type_name', path='$.pay_type_name', state='carry', type='string'),
            DeclarationEntry(name='m_delivery_type_name', path='$.m_delivery_type_name', state='carry', type='string'),
            DeclarationEntry(name='payment_type_name', path='$.payment_type_name', state='carry', type='string'),
            DeclarationEntry(name='audit', path='$.audit', state='carry', type='array'),
            DeclarationEntry(name='enable', path='$.enable', state='carry', type='string'),
            DeclarationEntry(name='policy_match', path='$.policy_match', state='carry', type='string'),
            DeclarationEntry(name='policy_match_name', path='$.policy_match_name', state='carry', type='string'),
            DeclarationEntry(name='real_discount_status_name', path='$.real_discount_status_name', state='carry', type='string'),
            DeclarationEntry(name='expect_discount_status_name', path='$.expect_discount_status_name', state='carry', type='string'),
            DeclarationEntry(name='expect_policy_status_name', path='$.expect_policy_status_name', state='carry', type='string'),
            DeclarationEntry(name='policy_status_name', path='$.policy_status_name', state='carry', type='string'),
            DeclarationEntry(name='subsidy_category_name', path='$.subsidy_category_name', state='carry', type='string'),
            DeclarationEntry(name='expect_subsidy_category_name', path='$.expect_subsidy_category_name', state='carry', type='string'),
            DeclarationEntry(name='real_subsidy_category_name', path='$.real_subsidy_category_name', state='carry', type='string'),
            DeclarationEntry(name='revoke_status_name', path='$.revoke_status_name', state='carry', type='string'),
            DeclarationEntry(name='revoke_type_name', path='$.revoke_type_name', state='carry', type='string'),
            DeclarationEntry(name='asset_status_name', path='$.asset_status_name', state='carry', type='string'),
            DeclarationEntry(name='order_file', path='$.order_file', state='carry', type='array'),
        ],
    ),
    responses={
        200: ResponseSpec(
            status=200,
            description="成功",
            declarations=[
                DeclarationEntry(name='code', path='$.code', type='integer', required=False, example=200, ui_kind='text', assertable=True),
                DeclarationEntry(name='msg', path='$.msg', type='string', required=False, example='成功', ui_kind='text', assertable=True),
                # 2026-09-05 结构化:$.data[0].* 深实例叶子升为整容器模板
                # children(响应侧实例级角标不做,模板态匹配,实例化归渲染器);
                # 行形状 9 键,example 同步同日抓包(订舱文件行,无 _XID)
                DeclarationEntry(name='data', path='$.data', type='array', required=False, assertable=True,
                    children=[
                        DeclarationEntry(name='client_company_id', path='$.data.client_company_id', type='string', required=False, example='335247043402399744', ui_kind='text', assertable=True),
                        DeclarationEntry(name='client_company_name', path='$.data.client_company_name', type='string', required=False, example='绍兴柯桥鹏达进出口有限公司', ui_kind='text', assertable=True),
                        DeclarationEntry(name='trustee_company_id', path='$.data.trustee_company_id', type='string', required=False, example='1', ui_kind='text', assertable=True),
                        DeclarationEntry(name='trustee_company_name', path='$.data.trustee_company_name', type='string', required=False, example='青岛易航道物流科技有限公司', ui_kind='text', assertable=True),
                        DeclarationEntry(name='document_type', path='$.data.document_type', type='string', required=False, example='BOOK_CUSTOMER', ui_kind='text', assertable=True),
                        DeclarationEntry(name='file_url', path='$.data.file_url', type='string', required=False, example='6a9c2d1e2292e.pdf', ui_kind='text', assertable=True),
                        DeclarationEntry(name='file_name', path='$.data.file_name', type='string', required=False, example='6a9c2d1e2292e.pdf', ui_kind='text', assertable=True),
                        DeclarationEntry(name='file_id', path='$.data.file_id', type='string', required=False, example='354640409386812416', ui_kind='text', assertable=True),
                        DeclarationEntry(name='file_type', path='$.data.file_type', type='string', required=False, example='PDF', ui_kind='text', assertable=True),
                    ]),
                DeclarationEntry(name='request_id', path='$.request_id', type='string', required=False, example='44a89db20b3ebd34718f4b3f4b7c24d8', ui_kind='text', assertable=True),
            ],        
        ),
    },
    version=FIN_DEFAULT_VERSION,
    metadata=EndpointMetadata(
        module=FIN_DEFAULT_MODULE,
        owner=FIN_DEFAULT_OWNER,
        tags=list(FIN_DEFAULT_TAGS),
    ),
)
