"""fin.order_entrust.order_add —— 委托订舱下单接口契约。在 scen_test_14 中出现4次。"""

from typing import Final

from gimbal_plate.systems.fin.system_info import (
    FIN_DEFAULT_AUTHOR,
    FIN_DEFAULT_MODULE,
    FIN_DEFAULT_OWNER,
    FIN_DEFAULT_PRIORITY,
    FIN_DEFAULT_TAGS,
    FIN_DEFAULT_VERSION,
    FIN_SYSTEM,
)

from gimbal_plate.schema.endpoint import (
    ApiSpec,
    EndpointSpec,
    DeclarationEntry,
    RequestSpec,
    ResponseSpec,
    EndpointMetadata,
)

# ----------------------------------------------------------------------
# 来源: curl 导入 | 生成时间: 2026-09-01T07:29:13.326038+00:00
# 人工已确认: 类型/必填/绑定面/响应语义/能力声明
# 原始 curl(认证信息已脱敏):
#   curl --url 'https://fin-tidb.21eflag.com/api/order/orderEntrust/orderAdd'    -H 'Accept: application/json, text/plain, */*'    -H 'Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7'    -H 'Authorization: ***REDACTED***'    -H 'Connection: keep-alive'    -H 'Content-Type: application/json;charset=UTF-8'    -H 'Origin: https://fin-tidb.21eflag.com'    -H 'Referer: https://fin-tidb.21eflag.com/'    -H 'Sec-Fetch-Dest: empty'    -H 'Sec-Fetch-Mode: cors'    -H 'Sec-Fetch-Site: same-origin'    -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36 Edg/151.0.0.0'    -H 'sec-ch-ua: "Not=A?Brand";v="99", "Microsoft Edge";v="151", "Chromium";v="151"'    -H 'sec-ch-ua-mobile: ?0'    -H 'sec-ch-ua-platform: "Windows"'    -b 'rememberMe=true; username=18180789650; PHPSESSID=grfb3ngdiae9pd44ihj91v8arr; think_language=zh-CN; password=iwyIYO3mqqLwnODZDxadCzUvLk9TMoJxrB/O1ubK4TAi8H0niCTrbccYl+4EHD+4h0JdPvRGPnkY/4mMY70Evw==; Admin-Token=***REDACTED***'    --data-raw '{"client_expand_name":"孙奉盛","client_expand_id":"41","m_delivery_type":"","customer_id":"335247043402399744","customer_name":"","receive_time_limit":"5","deposit_refund_day":"60","deposit_settlement_date":"30","service_id":"41","service_name":"孙奉盛","sale_id":"795","sale_name":"孙奉盛运营","operator_id":"786","operator_name":"","customer_contact_id":"335247043675029504","customer_contact_name":"","main_sort":"易航道-易汇联","policy_id":"295502731957764096","policy_name":"sfs易航道-易汇联","policy_type":"JSZX","settle_type":"1","settle_type_name":"月结","product_id":"2","product_name":"月结-延长-无保证金","deposit_type":"2","deposit_type_name":"无","period_delay_type":"1","period_delay_type_name":"延长","service_items":["booking_space"],"business_type":"1","trade_term":"","carrier":"ONE","carrier_id":"110","bl_no":"Codfish_TEST_001","track_bl_no":"Codfish_TEST_001","etd":1785945600,"atd":1786377600,"ship_name":"ONE SAN DIEGO","voy":"6275","pol":"QINGDAO,CHINA","pot":"AOSHANWEI,CHINA","pod":"FREMANTLE,AUSTRALIA","del":"FREMANTLE,AUSTRALIA","country_name":"AUSTRALIA","airline_type":"澳洲","ocean_type":"远洋","terms_payment":"T/T","terms_transport":"CY/CY","pay_type":"FREIGHT PREPAID","customer_order_sn":"","terms_shipment":"测试装运条款","shipper":"测试发货人","consignee":"测试收货人","notifier":"测试通知人","ship_mark":"测试唛头","commodity":"测试品名","notes":"测试备注","cargo_type":"goods","packer":"测试包装","num":"1","gross_weight":"1.00","bulk":"999","sea_trans_cost":"","teu":"","volume":"","volume_desc":"","order_sn":"","status":"1","sea_trans_currency":"USD","container":[],"message_board":[],"customer_file_list":[],"supplier":[{"is_manual":"","is_primary":"1","isset_fee":"0","isset_supplier":"1","order_id":"","order_supplier_id":"","service_item":"booking_space","service_item_name":"订舱","settle_object_id":"15","settlement_date":null,"pay_time_limit":"10","supplier_id":"1","supplier_name":"山东旭禾国际贸易有限公司","supplier_pay_date":null,"supplier_period":null,"user_id":"41","user_name":"孙奉盛","settle_type":"1","supplier_name_clean":"山东旭禾国际贸易有限公司","supplier_name_en":"","tax_number":"91370811MA3F04A516","settle_object":"山东旭禾国际贸易有限公司","settle_object_clean":"山东旭禾国际贸易有限公司","settle_type_name":"月结"}],"remark":"","payment_type_name":"确定性付款","payment_type":"1","policy_type_name":"","main_ids":"1,3","pot_cn":null,"pot_port_name":"AOSHANWEI,CHINA","pol_cn":"青岛港","pol_port_name":"QINGDAO,CHINA","pol_country_id":"1","pol_country":"CHINA","pol_country_cn":"中国","del_cn":"弗里曼特尔","del_port_name":"FREMANTLE,AUSTRALIA","pod_cn":"弗里曼特尔","pod_port_name":"FREMANTLE,AUSTRALIA","country_id":"673","country_name_cn":"澳大利亚","entrust_status":1,"order_file":[]}'
# ----------------------------------------------------------------------
ORDER_ENTRUST_ORDER_ADD: Final[EndpointSpec] = EndpointSpec(
    id='fin.order_entrust.order_add',
    system='fin',
    service='fin-service',
    name='委托订舱下单',
    description='委托订舱下单',
    api=ApiSpec(
        service='fin-service',
        method='POST',
        path='/api/order/orderEntrust/orderAdd',
        headers={},
        consumes=[],
        produces=[],
    ),
    request=RequestSpec(
        body_type='json',
        
        declarations=[
        DeclarationEntry(name='bl_no', path='$.bl_no', type='string', default='Codfish_TEST_001', example='Codfish_TEST_001', ui_kind='text'),
        DeclarationEntry(name='track_bl_no', path='$.track_bl_no', type='string', default='Codfish_TEST_001', example='Codfish_TEST_001', ui_kind='text'),
        DeclarationEntry(name='action', path='$.action', type='string', default='check', example='submit', description='check[校验]/submit[提交]', ui_kind='text'),
        DeclarationEntry(name='client_expand_name', path='$.client_expand_name', state='carry', type='string'),
        DeclarationEntry(name='client_expand_id', path='$.client_expand_id', state='carry', type='string'),
        DeclarationEntry(name='m_delivery_type', path='$.m_delivery_type', state='carry', type='string'),
        DeclarationEntry(name='customer_id', path='$.customer_id', state='carry', type='string'),
        DeclarationEntry(name='customer_name', path='$.customer_name', state='carry', type='string'),
        DeclarationEntry(name='receive_time_limit', path='$.receive_time_limit', state='carry', type='string'),
        DeclarationEntry(name='deposit_refund_day', path='$.deposit_refund_day', state='carry', type='string'),
        DeclarationEntry(name='deposit_settlement_date', path='$.deposit_settlement_date', state='carry', type='string'),
        DeclarationEntry(name='service_id', path='$.service_id', state='carry', type='string'),
        DeclarationEntry(name='service_name', path='$.service_name', state='carry', type='string'),
        DeclarationEntry(name='sale_id', path='$.sale_id', state='carry', type='string'),
        DeclarationEntry(name='sale_name', path='$.sale_name', state='carry', type='string'),
        DeclarationEntry(name='operator_id', path='$.operator_id', state='carry', type='string'),
        DeclarationEntry(name='operator_name', path='$.operator_name', state='carry', type='string'),
        DeclarationEntry(name='customer_contact_id', path='$.customer_contact_id', state='carry', type='string'),
        DeclarationEntry(name='customer_contact_name', path='$.customer_contact_name', state='carry', type='string'),
        DeclarationEntry(name='main_sort', path='$.main_sort', state='carry', type='string'),
        DeclarationEntry(name='policy_id', path='$.policy_id', state='carry', type='string'),
        DeclarationEntry(name='policy_name', path='$.policy_name', state='carry', type='string'),
        DeclarationEntry(name='policy_type', path='$.policy_type', state='carry', type='string'),
        DeclarationEntry(name='settle_type', path='$.settle_type', state='carry', type='string'),
        DeclarationEntry(name='settle_type_name', path='$.settle_type_name', state='carry', type='string'),
        DeclarationEntry(name='product_id', path='$.product_id', state='carry', type='string'),
        DeclarationEntry(name='product_name', path='$.product_name', state='carry', type='string'),
        DeclarationEntry(name='deposit_type', path='$.deposit_type', state='carry', type='string'),
        DeclarationEntry(name='deposit_type_name', path='$.deposit_type_name', state='carry', type='string'),
        DeclarationEntry(name='period_delay_type', path='$.period_delay_type', state='carry', type='string'),
        DeclarationEntry(name='period_delay_type_name', path='$.period_delay_type_name', state='carry', type='string'),
        DeclarationEntry(name='service_items', path='$.service_items', state='carry', type='array'),
        DeclarationEntry(name='business_type', path='$.business_type', state='carry', type='string'),
        DeclarationEntry(name='trade_term', path='$.trade_term', state='carry', type='string'),
        DeclarationEntry(name='carrier', path='$.carrier', state='carry', type='string'),
        DeclarationEntry(name='carrier_id', path='$.carrier_id', state='carry', type='string'),
        DeclarationEntry(name='etd', path='$.etd', state='carry', type='integer'),
        DeclarationEntry(name='atd', path='$.atd', state='carry', type='integer'),
        DeclarationEntry(name='ship_name', path='$.ship_name', state='carry', type='string'),
        DeclarationEntry(name='voy', path='$.voy', state='carry', type='string'),
        DeclarationEntry(name='pol', path='$.pol', state='carry', type='string'),
        DeclarationEntry(name='pot', path='$.pot', state='carry', type='string'),
        DeclarationEntry(name='pod', path='$.pod', state='carry', type='string'),
        DeclarationEntry(name='del', path='$.del', state='carry', type='string'),
        DeclarationEntry(name='country_name', path='$.country_name', state='carry', type='string'),
        DeclarationEntry(name='airline_type', path='$.airline_type', state='carry', type='string'),
        DeclarationEntry(name='ocean_type', path='$.ocean_type', state='carry', type='string'),
        DeclarationEntry(name='terms_payment', path='$.terms_payment', state='carry', type='string'),
        DeclarationEntry(name='terms_transport', path='$.terms_transport', state='carry', type='string'),
        DeclarationEntry(name='pay_type', path='$.pay_type', state='carry', type='string'),
        DeclarationEntry(name='customer_order_sn', path='$.customer_order_sn', state='carry', type='string'),
        DeclarationEntry(name='terms_shipment', path='$.terms_shipment', state='carry', type='string'),
        DeclarationEntry(name='shipper', path='$.shipper', state='carry', type='string'),
        DeclarationEntry(name='consignee', path='$.consignee', state='carry', type='string'),
        DeclarationEntry(name='notifier', path='$.notifier', state='carry', type='string'),
        DeclarationEntry(name='ship_mark', path='$.ship_mark', state='carry', type='string'),
        DeclarationEntry(name='commodity', path='$.commodity', state='carry', type='string'),
        DeclarationEntry(name='notes', path='$.notes', state='carry', type='string'),
        DeclarationEntry(name='cargo_type', path='$.cargo_type', state='carry', type='string'),
        DeclarationEntry(name='packer', path='$.packer', state='carry', type='string'),
        DeclarationEntry(name='num', path='$.num', state='carry', type='string'),
        DeclarationEntry(name='gross_weight', path='$.gross_weight', state='carry', type='string'),
        DeclarationEntry(name='bulk', path='$.bulk', state='carry', type='string'),
        DeclarationEntry(name='sea_trans_cost', path='$.sea_trans_cost', state='carry', type='string'),
        DeclarationEntry(name='teu', path='$.teu', state='carry', type='string'),
        DeclarationEntry(name='volume', path='$.volume', state='carry', type='string'),
        DeclarationEntry(name='volume_desc', path='$.volume_desc', state='carry', type='string'),
        DeclarationEntry(name='order_sn', path='$.order_sn', state='carry', type='string'),
        DeclarationEntry(name='status', path='$.status', state='carry', type='string'),
        DeclarationEntry(name='sea_trans_currency', path='$.sea_trans_currency', state='carry', type='string'),
        DeclarationEntry(name='container', path='$.container', state='carry', type='array'),
        DeclarationEntry(name='message_board', path='$.message_board', state='carry', type='array'),
        DeclarationEntry(name='customer_file_list', path='$.customer_file_list', state='carry', type='array'),
        DeclarationEntry(name='supplier', path='$.supplier', state='carry', type='array'),
        DeclarationEntry(name='remark', path='$.remark', state='carry', type='string'),
        DeclarationEntry(name='payment_type_name', path='$.payment_type_name', state='carry', type='string'),
        DeclarationEntry(name='payment_type', path='$.payment_type', state='carry', type='string'),
        DeclarationEntry(name='policy_type_name', path='$.policy_type_name', state='carry', type='string'),
        DeclarationEntry(name='main_ids', path='$.main_ids', state='carry', type='string'),
        DeclarationEntry(name='pot_cn', path='$.pot_cn', state='carry', type='string'),
        DeclarationEntry(name='pot_port_name', path='$.pot_port_name', state='carry', type='string'),
        DeclarationEntry(name='pol_cn', path='$.pol_cn', state='carry', type='string'),
        DeclarationEntry(name='pol_port_name', path='$.pol_port_name', state='carry', type='string'),
        DeclarationEntry(name='pol_country_id', path='$.pol_country_id', state='carry', type='string'),
        DeclarationEntry(name='pol_country', path='$.pol_country', state='carry', type='string'),
        DeclarationEntry(name='pol_country_cn', path='$.pol_country_cn', state='carry', type='string'),
        DeclarationEntry(name='del_cn', path='$.del_cn', state='carry', type='string'),
        DeclarationEntry(name='del_port_name', path='$.del_port_name', state='carry', type='string'),
        DeclarationEntry(name='pod_cn', path='$.pod_cn', state='carry', type='string'),
        DeclarationEntry(name='pod_port_name', path='$.pod_port_name', state='carry', type='string'),
        DeclarationEntry(name='country_id', path='$.country_id', state='carry', type='string'),
        DeclarationEntry(name='country_name_cn', path='$.country_name_cn', state='carry', type='string'),
        DeclarationEntry(name='entrust_status', path='$.entrust_status', type='integer',default='',example='1',description='1是检查，2是分发',ui_kind='text'),
        DeclarationEntry(name='order_file', path='$.order_file', state='carry', type='array'),
        ],
    ),
    responses={
        200: ResponseSpec(
            status=200,
        ),
    },   
    version=FIN_DEFAULT_VERSION,
    metadata=EndpointMetadata(
        module=FIN_DEFAULT_MODULE,
        owner=FIN_DEFAULT_OWNER,
        tags=list(FIN_DEFAULT_TAGS),
    ),
)
